"""The records that get a figure: 3 that need one to be answered, the 88 the
diagrams audit found would benefit, the 72 of diagram batch 1, the 31 of
diagram batch 2 and the 152 of diagram batch 3.

id: (tier, topic, family). Tiers: R required, A high, B medium, C low. From docs/DIAGRAMS_AUDIT.md
(batch 1: section 8, batch 2: section 9, batch 3: section 10).
"""

NEED = {
    'final-exam-#1-005': ('R', 'Troubleshooting a switch/lamp circuit (meter readings)', 'Required exam figure'),
    'final-exam-#1-013': ('R', 'Meter hookups: which one is an ammeter', 'Required exam figure'),
    'final-exam-#1-047': ('R', 'Control symbols: temperature-actuated switch', 'Required exam figure'),
    'final-exam-#1-020': ('A', '250.53(A)(3) rod spacing 6 ft', 'F1 Grounding electrode system + service bonding'),
    'open-book-exam-#1-008': ('A', '250.53(A)(5) plate electrode depth 30 in', 'F1 Grounding electrode system + service bonding'),
    'open-book-exam-#10-024': ('A', 'Grounding electrode conductor (definition)', 'F1 Grounding electrode system + service bonding (P4, GEC masked)'),
    'open-book-exam-#1-002': ('A', 'Main bonding jumper (definition, 250.28)', 'F1 Grounding electrode system + service bonding (PROTOTYPE P4)'),
    'open-book-exam-#1-010': ('A', '210.8(A) receptacles within 6 ft of tub/shower', 'F10 Dwelling GFCI location map'),
    'final-exam-#1-051': ('A', '110.26(C)(3) personnel door 25 ft, 800 A', 'F2 110.26 working space family'),
    'open-book-exam-#10-016': ('A', '110.26(A)(1) Condition 2 (concrete = grounded)', 'F2 110.26 working space family'),
    'open-book-exam-#7-022': ('A', '110.26 open doors impede access (24 in / 6 1/2 ft)', 'F2 110.26 working space family'),
    'final-exam-#1-057': ('A', '110.26(E)(1) dedicated space', 'F2 110.26 working space family (PROTOTYPE P1)'),
    'final-exam-#1-043': ('A', '680.43(B)(1)(a) spa paddle fan 12 ft', 'F3 Pool / spa / fountain clearances'),
    'final-exam-#1-060': ('A', '680.11(A) underground wiring within 5 ft of pool', 'F3 Pool / spa / fountain clearances'),
    'final-exam-#3-059': ('A', '680.22(A)(2) pump receptacle 6 ft from pool', 'F3 Pool / spa / fountain clearances'),
    'open-book-exam-#4-011': ('A', '680.43(B)(1)(a) spa paddle fan 12 ft', 'F3 Pool / spa / fountain clearances'),
    'final-exam-#3-013': ('A', '358.30(A) EMT fastening 3 ft / 5 ft', 'F4 Raceway and cable support spacing'),
    'final-exam-#1-049': ('A', 'Table 300.5(A) cover under 2 in concrete', 'F5 Burial cover (Table 300.5(A)) (PROTOTYPE P3)'),
    'open-book-exam-#4-004': ('A', 'Table 300.5(A) cover under 2 in concrete', 'F5 Burial cover (Table 300.5(A)) (PROTOTYPE P3)'),
    'final-exam-#1-011': ('A', '210.52(A)(2) 24 in wall space', 'F6 Dwelling receptacle placement plan'),
    'final-exam-#1-008': ('A', '210.52(E)(3) deck receptacle max height', 'F7 Balcony/deck receptacle height (PROTOTYPE P2)'),
    'open-book-exam-#10-020': ('A', '210.52(E)(3) deck receptacle max height', 'F7 Balcony/deck receptacle height (PROTOTYPE P2)'),
    'final-exam-#1-053': ('A', '225.18(5) railroad clearance 24 1/2 ft', 'F8 Overhead clearance ladder'),
    'open-book-exam-#10-010': ('A', '225.19(D) 3 ft from openings, material-handling door', 'F8 Overhead clearance ladder'),
    'final-exam-#1-055': ('A', '300.4(D) 1 1/4 in from framing edge', 'F9 Stud/framing protection'),
    'open-book-exam-#1-004': ('A', '300.4(A)(2) 1/16 in steel plate in notches', 'F9 Stud/framing protection'),
    'final-exam-#1-035': ('B', '250.52(A)(2) in-ground steel 10 ft', 'F1 Grounding electrode system + service bonding'),
    'final-exam-#3-027': ('B', '250.66(B) GEC to concrete-encased electrode, #4 Cu', 'F1 Grounding electrode system + service bonding'),
    'final-exam-#3-050': ('B', '250.68(B) bonding around water meter / insulated joints', 'F1 Grounding electrode system + service bonding'),
    'open-book-exam-#4-024': ('B', '250.52(A)(2) in-ground steel 10 ft', 'F1 Grounding electrode system + service bonding'),
    'final-exam-#1-012': ('B', '210.8(A)(2) garage GFCI', 'F10 Dwelling GFCI location map'),
    'final-exam-#3-006': ('B', '210.8(C) crawl space lighting outlets', 'F10 Dwelling GFCI location map'),
    'final-exam-#3-064': ('B', '210.8(A) laundry/garage/shower', 'F10 Dwelling GFCI location map'),
    'open-book-exam-#1-014': ('B', '210.8(C) crawl space lighting outlets', 'F10 Dwelling GFCI location map'),
    'open-book-exam-#4-002': ('B', '210.8(F) outdoor outlets', 'F10 Dwelling GFCI location map'),
    'open-book-exam-#1-011': ('B', '110.26(B) guarded working space in a passageway', 'F2 110.26 working space family'),
    'final-exam-#1-024': ('B', '680.58 fountain receptacles 20 ft', 'F3 Pool / spa / fountain clearances'),
    'final-exam-#3-007': ('B', '680.35(D) storable pool audio 6 ft', 'F3 Pool / spa / fountain clearances'),
    'final-exam-#1-066': ('B', '330.30(D)(2) MC unsupported 72 in', 'F4 Raceway and cable support spacing'),
    'final-exam-#3-053': ('B', '344.30(B)(2) RMC 1 in, 12 ft', 'F4 Raceway and cable support spacing'),
    'final-exam-#5-006': ('B', '320.30(D)(2) AC unsupported 2 ft', 'F4 Raceway and cable support spacing'),
    'final-exam-#5-053': ('B', '384.30(A) strut channel 10 ft / 3 ft', 'F4 Raceway and cable support spacing'),
    'final-exam-#5-069': ('B', '334.30(B)(2) NM in access ceiling 54 in', 'F4 Raceway and cable support spacing'),
    'final-exam-#5-070': ('B', 'Table 352.30(B) PVC 1/2 in, 3 ft', 'F4 Raceway and cable support spacing'),
    'final-exam-#1-003': ('B', '210.63(B)(1) service receptacle, same room', 'F6 Dwelling receptacle placement plan'),
    'final-exam-#1-022': ('B', '210.52(G)(1) garage receptacles', 'F6 Dwelling receptacle placement plan'),
    'final-exam-#1-031': ('B', '210.52(H) hallway 10 ft', 'F6 Dwelling receptacle placement plan'),
    'final-exam-#3-035': ('B', '210.50(C) appliance outlet within 6 ft', 'F6 Dwelling receptacle placement plan'),
    'final-exam-#3-049': ('B', '210.63 receptacle within 25 ft', 'F6 Dwelling receptacle placement plan'),
    'open-book-exam-#1-005': ('B', '210.63 receptacle within 25 ft', 'F6 Dwelling receptacle placement plan'),
    'open-book-exam-#1-016': ('B', '210.63(B)(1) service receptacle, same room', 'F6 Dwelling receptacle placement plan'),
    'open-book-exam-#1-022': ('B', '210.50(C) appliance outlet within 6 ft', 'F6 Dwelling receptacle placement plan'),
    'final-exam-#1-050': ('B', '800.44(B) 8 ft over roofs', 'F8 Overhead clearance ladder'),
    'final-exam-#3-031': ('B', '800.44 overhead communications entering buildings', 'F8 Overhead clearance ladder'),
    'final-exam-#1-028': ('B', '514.11(A) fuel dispenser shutoff 20-100 ft', 'Single-purpose figure'),
    'final-exam-#1-029': ('B', '408.5 conduit stub-up 3 in', 'Single-purpose figure'),
    'final-exam-#1-032': ('B', '240.21(B)(1) 10 ft tap', 'Single-purpose figure'),
    'final-exam-#1-052': ('B', '550.32(F) mobile home disconnect 24 in', 'Single-purpose figure'),
    'final-exam-#1-065': ('B', 'Sine wave, 90 degrees of a 60 Hz cycle', 'Single-purpose figure'),
    'final-exam-#3-047': ('B', '230.54(B) SE cable gooseneck (name masked)', 'Single-purpose figure'),
    'final-exam-#3-051': ('B', '550.32(F) mobile home disconnect 24 in', 'Single-purpose figure'),
    'final-exam-#3-055': ('B', 'Two resistors in parallel (value masked)', 'Single-purpose figure'),
    'final-exam-#5-052': ('B', '368.17(B) busway reduction', 'Single-purpose figure'),
    'open-book-exam-#1-001': ('B', '210.4(B) multiwire branch circuit', 'Single-purpose figure'),
    'open-book-exam-#10-013': ('B', '314.23(E) box supported by two conduits', 'Single-purpose figure'),
    'open-book-exam-#4-008': ('B', '210.4(C) multiwire branch circuit, line-to-neutral', 'Single-purpose figure'),
    'open-book-exam-#4-018': ('B', '312.5(C) Ex. 1 nipple 18 in - 10 ft', 'Single-purpose figure'),
    'open-book-exam-#7-024': ('B', '408.3(F)(1) high-leg delta marking', 'Single-purpose figure'),
    'open-book-exam-#1-012': ('C', '210.8(B)(3) sink + food prep areas', 'F10 Dwelling GFCI location map'),
    'open-book-exam-#4-021': ('C', '210.8(A) Ex. snow-melting receptacles', 'F10 Dwelling GFCI location map'),
    'final-exam-#5-065': ('C', '376.30(B) vertical wireway 15 ft', 'F4 Raceway and cable support spacing'),
    'final-exam-#5-067': ('C', '342.30(B)(3) IMC riser 20 ft', 'F4 Raceway and cable support spacing'),
    'open-book-exam-#7-013': ('C', 'Table 300.5(A) (reference-seeking: post-answer only)', 'F5 Burial cover (Table 300.5(A))'),
    'final-exam-#3-020': ('C', '810.13 antenna lead-in 2 ft from power', 'F8 Overhead clearance ladder'),
    'final-exam-#1-023': ('C', '250.122(F) EGC in each parallel raceway', 'Single-purpose figure'),
    'final-exam-#1-033': ('C', 'Three-way switch = SPDT (post-answer)', 'Single-purpose figure'),
    'final-exam-#1-041': ('C', 'Stop button in series (post-answer)', 'Single-purpose figure'),
    'final-exam-#1-042': ('C', '406.9(B) wet-location receptacle', 'Single-purpose figure'),
    'final-exam-#1-045': ('C', '422.16(B)(1) disposer cord 18-36 in', 'Single-purpose figure'),
    'final-exam-#1-062': ('C', 'Voltage drop panel-to-load', 'Single-purpose figure'),
    'final-exam-#1-063': ('C', 'Drawing scale 1/4 in = 1 ft', 'Single-purpose figure'),
    'final-exam-#1-067': ('C', 'Chapter 9 Note 4 nipple fill 60%', 'Single-purpose figure'),
    'final-exam-#3-034': ('C', '314.24(B)(5) box depth for a flush device', 'Single-purpose figure'),
    'final-exam-#3-070': ('C', 'Delta generator symbol (triangle masked)', 'Single-purpose figure'),
    'final-exam-#5-048': ('C', '366.100(E) gutter bare-part spacing', 'Single-purpose figure'),
    'final-exam-#5-049': ('C', '382.15(A) not within 2 in of floor', 'Single-purpose figure'),
    'final-exam-#5-064': ('C', '470.11 thermal barrier 12 in', 'Single-purpose figure'),
    'open-book-exam-#10-021': ('C', '695.12(D) fire pump parts 12 in above floor', 'Single-purpose figure'),
    'open-book-exam-#4-006': ('C', '422.16(B)(1) disposer cord 18-36 in', 'Single-purpose figure'),
    'open-book-exam-#4-014': ('C', '406.9(B) wet-location receptacle', 'Single-purpose figure'),
    'open-book-exam-#7-010': ('C', '424.36 wiring 2 in above heated ceiling', 'Single-purpose figure'),
    # Batch 1 (audits diagram gap scan, 2026-09-29): HIGH -> A, MEDIUM -> B.
    'final-exam-#1-014': ('B', 'Table 310.16 #12 THWN ampacity with ambient and 4 CCC', 'Batch 1 H02 Ampacity: counting current-carrying conductors and derating'),
    'final-exam-#1-027': ('B', 'Table 310.15(B)(1)(1) #10 THWN-2 ampacity at 112 F', 'Batch 1 H02 Ampacity: counting current-carrying conductors and derating'),
    'final-exam-#3-057': ('A', '310.15(F) Is the grounding conductor counted as current-carrying', 'Batch 1 H02 Ampacity: counting current-carrying conductors and derating'),
    'final-exam-#1-044': ('A', 'Article 100 Unintended hot-to-enclosure connection (definition)', 'Batch 1 H16 Fault path to a metal enclosure vs. short vs. open circuit'),
    'open-book-exam-#4-009': ('A', 'Article 100 Unintended hot-to-enclosure connection (definition)', 'Batch 1 H16 Fault path to a metal enclosure vs. short vs. open circuit'),
    'final-exam-#1-048': ('B', '406.12(1) Hallway receptacle: tamper-resistant', 'Batch 1 H03 Dwelling AFCI / tamper-resistant coverage map'),
    'open-book-exam-#4-005': ('B', '406.12(1) Hallway receptacle: tamper-resistant', 'Batch 1 H03 Dwelling AFCI / tamper-resistant coverage map'),
    'open-book-exam-#4-012': ('A', '210.12(A)(1) AFCI protects the entire ___', 'Batch 1 H03 Dwelling AFCI / tamper-resistant coverage map'),
    'open-book-exam-#4-023': ('A', '210.12(B), (C), and (D) AFCI receptacle locations (except ___)', 'Batch 1 H03 Dwelling AFCI / tamper-resistant coverage map'),
    'final-exam-#1-070': ('B', 'Table 430.250 Motor FLC from Table 430.250', 'Batch 1 H04 Motor branch circuit anatomy (Article 430)'),
    'final-exam-#3-009': ('A', '430.101 What the motor disconnect disconnects', 'Batch 1 H04 Motor branch circuit anatomy (Article 430)'),
    'final-exam-#3-038': ('B', '430.52(B) SCGF device must carry the ___ current', 'Batch 1 H04 Motor branch circuit anatomy (Article 430)'),
    'final-exam-#3-052': ('A', 'Table 430.37 Overload units for a three-phase motor', 'Batch 1 H04 Motor branch circuit anatomy (Article 430)'),
    'final-exam-#3-008': ('A', '500.5(D)(2) Fibers stored/handled outside manufacturing: class/division', 'Batch 1 H06 Hazardous locations: classes and divisions'),
    'open-book-exam-#10-017': ('B', '500.5(D) Class for ignitible fibers/flyings', 'Batch 1 H06 Hazardous locations: classes and divisions'),
    'final-exam-#1-061': ('B', '503.1 Class for ignitible fibers/flyings', 'Batch 1 H06 Hazardous locations: classes and divisions'),
    'final-exam-#3-019': ('A', '430.102(B)(1) Device in sight of motor and driven machinery', 'Batch 1 H05 Disconnect within sight of motor / A-C equipment'),
    'open-book-exam-#1-025': ('A', '440.14 A-C disconnect within sight and ___', 'Batch 1 H05 Disconnect within sight of motor / A-C equipment'),
    'final-exam-#3-029': ('B', 'Article 100 Localizing an overcurrent to the affected circuit (definition)', 'Batch 1 H07 Coordination of series overcurrent devices (one-line)'),
    'open-book-exam-#7-007': ('A', '708.54 Ex. Selective coordination exception for series devices', 'Batch 1 H07 Coordination of series overcurrent devices (one-line)'),
    'final-exam-#5-050': ('A', '368.234(A) Busway at building wall, over 1000 V', 'Batch 1 H08 Busway passing through an exterior wall (over 1000 V)'),
    'final-exam-#5-068': ('A', '344.10(C) RMC in cinder fill: concrete layer thickness', 'Batch 1 H09 Underground raceways: cinder fill and backfill'),
    'open-book-exam-#10-005': ('B', '300.5(F) Prohibited backfill (300.5(F))', 'Batch 1 H09 Underground raceways: cinder fill and backfill'),
    'open-book-exam-#10-025': ('B', '305.15(E) Prohibited backfill over 1000 V (305.15(E))', 'Batch 1 H09 Underground raceways: cinder fill and backfill'),
    'final-exam-#3-046': ('B', '408.7 Closing unused panelboard openings', 'Batch 1 H10 Panelboard interior: neutral terminals and unused openings'),
    'open-book-exam-#1-009': ('A', '408.41 Grounded conductor terminal in a panelboard', 'Batch 1 H10 Panelboard interior: neutral terminals and unused openings'),
    'open-book-exam-#1-003': ('A', '220.5(C) Floor area measured from which dimensions', 'Batch 1 H01 Floor area for load calculations (220.5(C))'),
    'open-book-exam-#10-002': ('A', '220.5(C) What dwelling square footage includes', 'Batch 1 H01 Floor area for load calculations (220.5(C))'),
    'open-book-exam-#7-016': ('B', '700.7(A) Sign for on-site emergency power sources', 'Batch 1 H12 Multiple supplies to one building: directories and signs'),
    'open-book-exam-#7-025': ('A', '225.37 Plaque/directory for multiple supplies', 'Batch 1 H12 Multiple supplies to one building: directories and signs'),
    'open-book-exam-#7-020': ('B', 'Article 100 Sign part that is not an electrical enclosure (definition)', 'Batch 1 H13 Electric sign construction'),
    'final-exam-#1-069': ('A', '600.9(C) Wood sign enclosure spacing from lampholders', 'Batch 1 H13 Electric sign construction'),
    'open-book-exam-#7-021': ('A', '408.36(B) Panel OCPD location when fed through a transformer', 'Batch 1 H11 Transformer-fed panelboard protection'),
    'open-book-exam-#10-011': ('A', '810.16(B) Antennas away from overhead power over ___ V', 'Batch 1 H14 Antenna clearance from overhead power lines'),
    'open-book-exam-#10-019': ('A', '517.18(B)(1) Receptacles at a Category 2 patient bed', 'Batch 1 H15 Hospital patient bed receptacles (517.18)'),
    'final-exam-#1-002': ('B', '408.18(C) Marking for rear/side field connections', 'Batch 1 M01 Switchboard sections and field-connection access'),
    'open-book-exam-#1-007': ('B', '408.3(A)(2) Conductors in a switchboard section', 'Batch 1 M01 Switchboard sections and field-connection access'),
    'open-book-exam-#1-015': ('B', '408.18(C) Marking for rear/side field connections', 'Batch 1 M01 Switchboard sections and field-connection access'),
    'final-exam-#1-026': ('B', 'Table 310.4(1) Meaning of -2 in RHW-2', 'Batch 1 M07 Insulation and cord letter decoder'),
    'final-exam-#1-034': ('B', 'Table 400.4 Cord type for wet and sunlight', 'Batch 1 M07 Insulation and cord letter decoder'),
    'final-exam-#5-022': ('B', '338.100 Cable type for direct burial', 'Batch 1 M07 Insulation and cord letter decoder'),
    'open-book-exam-#4-025': ('B', 'Table 400.4 and Note 9 Cord type for wet and sunlight', 'Batch 1 M07 Insulation and cord letter decoder'),
    'final-exam-#1-036': ('B', '310.12(A) Dwelling service conductor percentage', 'Batch 1 M08 Dwelling service/feeder conductor sizing (310.12)'),
    'final-exam-#3-065': ('B', '310.12(A) Where Table 310.12(A) applies', 'Batch 1 M08 Dwelling service/feeder conductor sizing (310.12)'),
    'open-book-exam-#4-022': ('B', '310.12(A) Dwelling service conductor percentage', 'Batch 1 M08 Dwelling service/feeder conductor sizing (310.12)'),
    'final-exam-#1-059': ('B', '210.18 What sets a branch-circuit rating', 'Batch 1 M09 Branch-circuit rating chain'),
    'final-exam-#3-014': ('B', 'Table 210.21(B)(2) Max cord load on 15 A receptacle, 20 A circuit', 'Batch 1 M09 Branch-circuit rating chain'),
    'open-book-exam-#7-011': ('B', '210.19(B) Conductor ampacity vs. branch-circuit rating', 'Batch 1 M09 Branch-circuit rating chain'),
    'final-exam-#3-024': ('B', '225.39(B) Disconnect rating, two 2-wire circuits', 'Batch 1 M13 Outbuilding disconnect ratings (225.39)'),
    'final-exam-#3-056': ('B', '225.39(A) Disconnect rating, one limited-load circuit', 'Batch 1 M13 Outbuilding disconnect ratings (225.39)'),
    'open-book-exam-#7-009': ('B', '225.39 Disconnect rating vs. load served', 'Batch 1 M13 Outbuilding disconnect ratings (225.39)'),
    'final-exam-#5-001': ('B', '324.41 FCC carpet square attachment', 'Batch 1 M18 Flat conductor cable (FCC) under carpet squares'),
    'final-exam-#5-004': ('B', '324.40(D) FCC connection to other wiring', 'Batch 1 M18 Flat conductor cable (FCC) under carpet squares'),
    'final-exam-#5-007': ('B', 'Article 100 FCC protective layer (definition)', 'Batch 1 M18 Flat conductor cable (FCC) under carpet squares'),
    'final-exam-#5-020': ('B', '332.104, 332.108, and 332.116 MI cable construction', 'Batch 1 M19 Cable and conductor construction cutaways'),
    'open-book-exam-#10-015': ('B', '310.3(B)(3) Copper-clad aluminum copper percentage', 'Batch 1 M19 Cable and conductor construction cutaways'),
    'final-exam-#5-003': ('B', 'Article 100 Armored / metal-sheathed cable type (definition)', 'Batch 1 M19 Cable and conductor construction cutaways'),
    'final-exam-#5-032': ('B', '348.22 Largest conductor in 3/8 in FMC', 'Batch 1 M21 Raceway fill percentages and 3/8 in FMC'),
    'final-exam-#5-066': ('B', '356.22 LFNC fill table in Chapter 9', 'Batch 1 M21 Raceway fill percentages and 3/8 in FMC'),
    'final-exam-#3-048': ('B', 'Table 348.22 Largest THHN in 3/8 in FMC', 'Batch 1 M21 Raceway fill percentages and 3/8 in FMC'),
    'final-exam-#1-040': ('B', 'Table 220.54 Demand factor, five dryers', 'Batch 1 M23 Dwelling appliance demand tables (220.54, 220.55)'),
    'open-book-exam-#4-015': ('B', 'Table 220.54 Demand factor, five dryers', 'Batch 1 M23 Dwelling appliance demand tables (220.54, 220.55)'),
    'final-exam-#1-021': ('B', 'Table 220.55 Demand load, 14 kW range', 'Batch 1 M23 Dwelling appliance demand tables (220.54, 220.55)'),
    'open-book-exam-#4-007': ('B', '406.3(E) Isolated ground receptacle marking', 'Batch 1 M26 Receptacle face markings and terminals'),
    'open-book-exam-#10-003': ('B', '406.10(C) Receptacle grounding terminal use', 'Batch 1 M26 Receptacle face markings and terminals'),
    'open-book-exam-#10-018': ('B', '406.3(E) Isolated ground receptacle marking', 'Batch 1 M26 Receptacle face markings and terminals'),
    'final-exam-#3-045': ('B', 'General knowledge AC cycles per second', 'Batch 1 R01 Reuse sine_wave_60hz_quarter_cycle'),
    'final-exam-#3-044': ('B', '647.4(D) Voltage drop, sensitive electronics', 'Batch 1 R02 Reuse voltage_drop_percent'),
    'final-exam-#3-066': ('B', '250.50 Concrete-encased electrode exemption', 'Batch 1 R03 Reuse electrode_system_250-52_250-53'),
    'open-book-exam-#1-018': ('B', '210.8(E) Which receptacles need GFCI under 210.8(E)', 'Batch 1 R04 Reuse equipment_receptacle_210-63'),
    'open-book-exam-#1-024': ('B', '680.21(C) and 680.5(B) Pool motor outlet GFCI amp limit', 'Batch 1 R05 Reuse pool_fountain_distances_680'),
    'open-book-exam-#10-004': ('B', '409.21 Industrial control panel supply conductors', 'Batch 1 R06 Reuse feeder_tap_10ft_240-21b1'),
    'final-exam-#1-004': ('B', 'Table 220.42(A) Office general lighting load, 5,000 sq ft', 'Batch 2 M02 General lighting load from floor area (Table 220.42(A))'),
    'open-book-exam-#1-021': ('B', 'Table 220.42(A) Office general lighting load, 5,000 sq ft', 'Batch 2 M02 General lighting load from floor area (Table 220.42(A))'),
    'final-exam-#1-019': ('B', 'General knowledge Meaning of I in W = E x I', 'Batch 2 M06 Ohms law / power wheel'),
    'final-exam-#3-033': ('B', 'General calculation Current from 2 W at 20 V DC', 'Batch 2 M06 Ohms law / power wheel'),
    'final-exam-#1-068': ('B', 'Table 250.122 EGC for a 50 A circuit', 'Batch 2 M10 EGC sizing from the OCPD (Table 250.122)'),
    'final-exam-#3-017': ('B', 'Table 250.122 EGC same size as circuit conductors', 'Batch 2 M10 EGC sizing from the OCPD (Table 250.122)'),
    'final-exam-#3-039': ('B', '422.12 Central heating equipment circuit type', 'Batch 2 M14 Single-load branch circuits (laundry, central heating)'),
    'open-book-exam-#1-020': ('B', '210.11(C)(2) Laundry branch circuit rating', 'Batch 2 M14 Single-load branch circuits (laundry, central heating)'),
    'final-exam-#3-063': ('B', '366.23(A) Busbar ampacity, 1 1/2 sq in', 'Batch 2 M16 Busbar cross-section ampacity (366.23(A))'),
    'final-exam-#5-039': ('B', '366.23(A) Busbar ampacity, 4 in x 1/2 in', 'Batch 2 M16 Busbar cross-section ampacity (366.23(A))'),
    'final-exam-#1-025': ('B', '630.12(A) Arc welder OCPD from I1max', 'Batch 2 M24 Welder supply calculations (Article 630)'),
    'final-exam-#3-040': ('B', '630.31(A)(2) Resistance welder supply ampacity', 'Batch 2 M24 Welder supply calculations (Article 630)'),
    'open-book-exam-#7-015': ('B', '310.15(A) Corrected ampacity limited by the end-connection rating', 'Batch 2 M25 Temperature limits at conductor end connections (110.14(C))'),
    'open-book-exam-#7-017': ('B', '110.14(C)(2) Pressure connector temperature rating', 'Batch 2 M25 Temperature limits at conductor end connections (110.14(C))'),
    'open-book-exam-#10-023': ('B', '551.71(B) RV sites with 30 A receptacles', 'Batch 2 M34 RV park supply (551.71, 551.72)'),
    'final-exam-#3-002': ('B', '551.72(B) RV feeder conductors, 208Y/120 V', 'Batch 2 M34 RV park supply (551.71, 551.72)'),
    'final-exam-#1-009': ('B', '310.6(C) Acceptable ungrounded conductor color', 'Batch 2 M03 Conductor color code'),
    'final-exam-#1-010': ('B', '220.14(H) 12 ft multioutlet assembly load', 'Batch 2 M04 Fixed multioutlet assembly load (220.14(H))'),
    'final-exam-#1-016': ('B', '590.4(J) Trees supporting holiday lighting spans', 'Batch 2 M05 Holiday lighting spans supported by trees (590.4(J))'),
    'final-exam-#3-015': ('B', '240.33 OCPD enclosure mounting position', 'Batch 2 M11 OCPD enclosure mounting position (240.33)'),
    'final-exam-#3-018': ('B', '440.64 Room A-C cord length, 120 V', 'Batch 2 M12 Room air conditioner cord (440.64)'),
    'final-exam-#3-060': ('B', '480.10(A) Battery gas ventilation', 'Batch 2 M15 Battery room ventilation (480.10(A))'),
    'final-exam-#3-069': ('B', '430.62(A) Feeder protection for motor group', 'Batch 2 M17 Feeder protection for a group of motors (430.62(A))'),
    'final-exam-#5-023': ('B', '336.24 TC shielded cable bending radius', 'Batch 2 M20 Cable bending radius (TC, 336.24)'),
    'open-book-exam-#4-019': ('B', '314.27(D) Ex. Screws for <= 6 lb equipment on a box', 'Batch 2 M27 Light equipment supported from a box (314.27(D) Ex.)'),
    'open-book-exam-#7-001': ('B', '200.3 Premises wiring connection to supply', 'Batch 2 M28 Grounded conductor continuity (200.3)'),
    'open-book-exam-#7-004': ('B', '517.73(B) Imaging equipment feeder demand', 'Batch 2 M29 Diagnostic imaging feeder demand (517.73(B))'),
    'open-book-exam-#7-005': ('B', 'Article 100 Highest water level before spilling (definition)', 'Batch 2 M30 Spa/hot tub water level term'),
    'open-book-exam-#7-008': ('B', '110.13(B) Openings that need free air circulation', 'Batch 2 M31 Free air circulation around equipment openings (110.13(B))'),
    'open-book-exam-#10-006': ('B', 'Article 100 Device that controls a disconnect through a relay (definition)', 'Batch 2 M32 Relay-operated control of a disconnect'),
    'open-book-exam-#10-008': ('B', '630.42(C) Welding cable tray sign text', 'Batch 2 M33 Welding cable tray signs (630.42(C))'),
    'final-exam-#2-001': ('A', '525.5(B)(2) Portable structures for fairs, carnivals and similar events shal...', 'Batch 3 N-H2 Portable fair structures near overhead power lines (525.5(B))'),
    'final-exam-#2-003': ('A', '250.52(A)(5) A copper-coated steel ground rod shall be at least ___.', 'Batch 3 N-H1 Driven electrodes: sizes and the three ways to install a rod'),
    'final-exam-#2-005': ('A', '250.53(A)(4) Where a rock bottom is encountered, the ground rod shall be perm...', 'Batch 3 N-H1 Driven electrodes: sizes and the three ways to install a rod'),
    'final-exam-#2-006': ('B', 'Article 100 A ___ is a portion of a sign that may provide protection from th...', 'Batch 3 repeat of open-book-exam-#7-020'),
    'final-exam-#2-008': ('A', '225.37 Where a building or structure has any combination of feeders, br...', 'Batch 3 repeat of open-book-exam-#7-025'),
    'final-exam-#2-009': ('B', 'Article 100 ___ is the highest level that water can reach before it spills o...', 'Batch 3 repeat of open-book-exam-#7-005'),
    'final-exam-#2-012': ('B', 'General knowledge In relation to a transformer, the ratio 20:1 indicates that ___.', 'Batch 3 N-M3 Transformer turns ratio'),
    'final-exam-#2-013': ('B', 'General knowledge In a parallel circuit, the voltage across each branch is ___ the...', 'Batch 3 N-M1 Series vs. parallel circuits: what is shared'),
    'final-exam-#2-014': ('B', 'General knowledge When a 60 watt bulb is connected in series with a 500 watt room...', 'Batch 3 N-M1 Series vs. parallel circuits: what is shared'),
    'final-exam-#2-015': ('B', 'General knowledge If the secondary voltage of a transformer is step-down, the prim...', 'Batch 3 N-M3 Transformer turns ratio'),
    'final-exam-#2-016': ('B', 'General knowledge In a parallel circuit with an unequal resistance on each branch...', 'Batch 3 N-M1 Series vs. parallel circuits: what is shared'),
    'final-exam-#2-017': ('B', 'General knowledge A circuit with a lagging current means the circuit is ___.', 'Batch 3 N-M2 AC waveforms: peak, effective, alternation, lead and lag'),
    'final-exam-#2-018': ('B', 'General knowledge The ___ value is considered as the most important value of a sin...', 'Batch 3 N-M2 AC waveforms: peak, effective, alternation, lead and lag'),
    'final-exam-#2-019': ('B', 'General calculation A wire has a resistance of 5 ohms. What will be the resistance o...', 'Batch 3 N-M4 What changes a conductors resistance'),
    'final-exam-#2-034': ('B', 'General knowledge An alternation is ___.', 'Batch 3 N-M2 AC waveforms: peak, effective, alternation, lead and lag'),
    'final-exam-#2-036': ('B', 'General knowledge If two equal resistance conductors are connected in parallel, th...', 'Batch 3 reuse parallel_resistors_equal'),
    'final-exam-#2-038': ('B', '210.18 Branch circuits recognized by this article shall be rated in acc...', 'Batch 3 reuse branch_circuit_rating_210'),
    'final-exam-#2-043': ('B', '300.5(F) Backfill that contains large rocks, paving materials, cinders, l...', 'Batch 3 repeat of open-book-exam-#10-005'),
    'final-exam-#2-044': ('B', '314.23(E) Enclosures that are not over 100 cubic inches in size and which...', 'Batch 3 repeat of open-book-exam-#10-013'),
    'final-exam-#2-045': ('B', '310.3(B)(3) Conductors drawn from a copper-clad aluminum rod with the copper...', 'Batch 3 repeat of open-book-exam-#10-015'),
    'final-exam-#2-046': ('A', '110.26(A)(1) Condition 2 Concrete, brick, or tile walls are considered as being ___.', 'Batch 3 repeat of open-book-exam-#10-016'),
    'final-exam-#2-047': ('B', '406.3(E) An isolated ground receptacle shall be identified by ___.', 'Batch 3 repeat of open-book-exam-#10-018'),
    'final-exam-#2-048': ('A', '517.18(B)(1) In a hospital Category 2 space, each patient bed location shall...', 'Batch 3 repeat of open-book-exam-#10-019'),
    'final-exam-#2-049': ('A', '210.52(E)(3) Balconies, decks, and porches that are attached to the dwelling...', 'Batch 3 repeat of open-book-exam-#10-020'),
    'final-exam-#2-055': ('B', 'General knowledge Which of the following will not affect the resistance of a circu...', 'Batch 3 N-M4 What changes a conductors resistance'),
    'final-exam-#2-056': ('B', 'General knowledge The voltage will lead the current when the ___ in the circuit.', 'Batch 3 N-M2 AC waveforms: peak, effective, alternation, lead and lag'),
    'final-exam-#2-059': ('A', '250.194(A) Where metal fences are located within ___ feet of the exposed el...', 'Batch 3 N-H3 Metal fence bonding near exposed live parts (250.194(A))'),
    'final-exam-#2-064': ('A', '430.102(B) If locating a motors disconnecting means within sight of the mot...', 'Batch 3 reuse in_sight_disconnect_430-102_440-14'),
    'final-exam-#2-065': ('B', '314.16(B)(4) A three-way switch is counted as ___ conductor(s) based on the l...', 'Batch 3 N-M5 Box fill: counting and volume (314.16)'),
    'final-exam-#4-003': ('B', '356.22 The number of conductors allowed in LFNC must not exceed that pe...', 'Batch 3 repeat of final-exam-#5-066'),
    'final-exam-#4-005': ('B', 'Table 314.16(A) Per the Code, the volume of a 3" x 2" x 2" device box is ___ cub...', 'Batch 3 N-M5 Box fill: counting and volume (314.16)'),
    'final-exam-#4-010': ('A', '210.52(D) A bathroom in a dwelling has a counter space of seven feet inclu...', 'Batch 3 N-H4 Kitchen counter, bathroom and outdoor receptacles (210.52(B)-(E))'),
    'final-exam-#4-011': ('B', 'Table 314.16(A) An installation requires a device box with a capacity of 10.25 c...', 'Batch 3 N-M5 Box fill: counting and volume (314.16)'),
    'final-exam-#4-012': ('B', '220.14(G) A show window is calculated at ___ va per linear foot.', 'Batch 3 N-H5 Show window receptacles and load (210.62, 220.14(G))'),
    'final-exam-#4-015': ('A', '210.52(E)(1) At least one receptacle outlet per unit, accessible at grade lev...', 'Batch 3 N-H4 Kitchen counter, bathroom and outdoor receptacles (210.52(B)-(E))'),
    'final-exam-#4-016': ('A', '210.52(B)(2) Which of the following receptacles may be connected to the small...', 'Batch 3 N-H4 Kitchen counter, bathroom and outdoor receptacles (210.52(B)-(E))'),
    'final-exam-#4-021': ('B', 'Table 314.16(B)(1) What size octagon box is required for 5 - #12 and 4 - #14 conduc...', 'Batch 3 N-M5 Box fill: counting and volume (314.16)'),
    'final-exam-#4-022': ('B', 'Table 4, Chapter 9 Assuming that the area of all the conductors (over 4 conductors)...', 'Batch 3 N-M7 Conduit fill: conductor areas against the 40% column'),
    'final-exam-#4-023': ('B', 'Table 220.55 When sizing the service conductors for an apartment complex, the...', 'Batch 3 N-M8 Ranges, ovens and dryers: demand columns (Table 220.55, 220.54)'),
    'final-exam-#4-024': ('B', 'Table 310.15(C)(1) The ampacity of a #14 THW conductor, when there are six conducto...', 'Batch 3 N-M6 Ampacity: ambient correction and conductor-count adjustment'),
    'final-exam-#4-025': ('B', 'Table 220.55 In a custom house, the demand load (load applied for service cal...', 'Batch 3 N-M8 Ranges, ovens and dryers: demand columns (Table 220.55, 220.54)'),
    'final-exam-#4-026': ('B', 'Table 430.248 The branch circuit conductor supplying a 3/4 hp, 1ø 115 volt mot...', 'Batch 3 N-M9 Motor circuit sizing by percentages (Article 430)'),
    'final-exam-#4-027': ('B', '220.5(C) You are wiring a house that has 2200 square feet under the roof....', 'Batch 3 N-M10 Dwelling general lighting and small-appliance load (220.41, 220.52, 220.53)'),
    'final-exam-#4-028': ('B', '220.52 When sizing the service on a dwelling unit, the small appliance...', 'Batch 3 N-M10 Dwelling general lighting and small-appliance load (220.41, 220.52, 220.53)'),
    'final-exam-#4-030': ('B', '430.24 The feeder carrying two single phase, 1 1/2 hp, 230v motors woul...', 'Batch 3 N-M9 Motor circuit sizing by percentages (Article 430)'),
    'final-exam-#4-031': ('B', 'Table 310.15(B)(1)(1) What is the allowable ampacity of a #12 TW copper conductor in a...', 'Batch 3 N-M6 Ampacity: ambient correction and conductor-count adjustment'),
    'final-exam-#4-032': ('B', 'Table 430.52(C)(1) The branch-circuit protection for a 1ø, 115v, 3 hp motor would n...', 'Batch 3 N-M9 Motor circuit sizing by percentages (Article 430)'),
    'final-exam-#4-033': ('B', 'Table 310.15(C)(1) The ampacity of a #14 THW conductor, when there are six conducto...', 'Batch 3 N-M6 Ampacity: ambient correction and conductor-count adjustment'),
    'final-exam-#4-034': ('B', '430.32(C) The maximum motor-running overload protection would be ___ amps...', 'Batch 3 N-M9 Motor circuit sizing by percentages (Article 430)'),
    'final-exam-#4-035': ('B', 'Table 310.15(B)(1)(1) The correction factor (C.F.) for 104°F is ___ for a 60°C insulat...', 'Batch 3 N-M6 Ampacity: ambient correction and conductor-count adjustment'),
    'final-exam-#4-036': ('B', 'Table 220.55 The branch-circuit load for one 6 kW oven would be ___ kW.', 'Batch 3 N-M8 Ranges, ovens and dryers: demand columns (Table 220.55, 220.54)'),
    'final-exam-#4-037': ('B', '430.32(C) If the full load current of a 2 hp, 115v, 1ø motor with a servic...', 'Batch 3 N-M9 Motor circuit sizing by percentages (Article 430)'),
    'final-exam-#4-038': ('B', '314.16(B) What is the cubic inch capacity required for a device box contai...', 'Batch 3 N-M5 Box fill: counting and volume (314.16)'),
    'final-exam-#4-039': ('B', 'Table 430.250 The branch circuit conductor supplying a 10 hp 3ø 230v motor sha...', 'Batch 3 N-M9 Motor circuit sizing by percentages (Article 430)'),
    'final-exam-#4-040': ('B', 'Table 310.15(C)(1) There are seven current carrying #12 THHN conductors run in a co...', 'Batch 3 N-M6 Ampacity: ambient correction and conductor-count adjustment'),
    'final-exam-#4-041': ('B', 'Table 310.16 The ampacity of a #12 THW conductor when there are not more than...', 'Batch 3 N-M6 Ampacity: ambient correction and conductor-count adjustment'),
    'final-exam-#4-042': ('B', '220.53 A 10 unit apartment building has a 4.5 kW water heater in each u...', 'Batch 3 N-M10 Dwelling general lighting and small-appliance load (220.41, 220.52, 220.53)'),
    'final-exam-#4-045': ('B', 'Table 220.55 A feeder supplying two 4 kW wall-mounted ovens and a 5 kW counte...', 'Batch 3 N-M8 Ranges, ovens and dryers: demand columns (Table 220.55, 220.54)'),
    'final-exam-#4-046': ('B', 'Table 220.54 What is the feeder neutral demand for six - 4.5 kW household clo...', 'Batch 3 N-M8 Ranges, ovens and dryers: demand columns (Table 220.55, 220.54)'),
    'final-exam-#4-047': ('B', '220.41 A dwelling has a total of 2500 sq. ft. How many 15 amp circuits...', 'Batch 3 N-M10 Dwelling general lighting and small-appliance load (220.41, 220.52, 220.53)'),
    'final-exam-#4-048': ('B', '220.41 An owner wishes to add 12 receptacle outlets to the drawings of...', 'Batch 3 N-M10 Dwelling general lighting and small-appliance load (220.41, 220.52, 220.53)'),
    'final-exam-#4-049': ('B', 'Table 220.55 The minimum demand load in kW for 15 - 3.5 kW ovens in an apartm...', 'Batch 3 N-M8 Ranges, ovens and dryers: demand columns (Table 220.55, 220.54)'),
    'final-exam-#4-050': ('B', 'Table 5, Chapter 9 The approximate area in square inches of a #14 RHH conductor wit...', 'Batch 3 N-M7 Conduit fill: conductor areas against the 40% column'),
    'final-exam-#4-051': ('B', 'Table 220.55 The minimum branch circuit demand for one 8 kW range in a reside...', 'Batch 3 N-M8 Ranges, ovens and dryers: demand columns (Table 220.55, 220.54)'),
    'final-exam-#4-052': ('A', '220.5(C) What is the general lighting load for a single dwelling that mea...', 'Batch 3 reuse floor_area_220-5c'),
    'final-exam-#4-053': ('B', 'Table 430.52(C)(1) Which of these dual-element fuse sizes does the Code permit for...', 'Batch 3 N-M9 Motor circuit sizing by percentages (Article 430)'),
    'final-exam-#4-054': ('B', '314.16(B)(5) The volume required for two #12 TW grounding conductors and two...', 'Batch 3 N-M5 Box fill: counting and volume (314.16)'),
    'final-exam-#4-055': ('B', 'Table 250.122 What is the minimum size copper equipment grounding conductor re...', 'Batch 3 reuse egc_size_250-122'),
    'final-exam-#4-056': ('B', '430.32(C) What is the maximum size overload relay permitted for protection...', 'Batch 3 N-M9 Motor circuit sizing by percentages (Article 430)'),
    'final-exam-#4-057': ('B', 'Table 5, Chapter 9 The total area of 6 - #8 XHHW conductors and 2 - #6 XHHW conduct...', 'Batch 3 N-M7 Conduit fill: conductor areas against the 40% column'),
    'final-exam-#4-059': ('B', 'Table 4, Chapter 9 How much space remains to be filled without exceeding the percen...', 'Batch 3 N-M7 Conduit fill: conductor areas against the 40% column'),
    'final-exam-#4-060': ('B', 'Table 4, Chapter 9 How many #8 TW conductors can be installed in a 1" IMC conduit,...', 'Batch 3 N-M7 Conduit fill: conductor areas against the 40% column'),
    'final-exam-#4-061': ('B', 'Table 430.52(C)(1) A 5 hp, single-phase, 230 volt, wound rotor motor would have non...', 'Batch 3 N-M9 Motor circuit sizing by percentages (Article 430)'),
    'final-exam-#4-062': ('B', 'Table 4, Chapter 9 How many #6 XHHW can be installed in a 2" PVC schedule 80 condui...', 'Batch 3 N-M7 Conduit fill: conductor areas against the 40% column'),
    'final-exam-#4-063': ('B', 'Table 310.15(C)(1) What is the ampacity of each conductor of a group of nine #14 RH...', 'Batch 3 N-M6 Ampacity: ambient correction and conductor-count adjustment'),
    'final-exam-#4-064': ('B', 'Table 314.16(B)(1) What is the minimum volume required for a box containing three -...', 'Batch 3 N-M5 Box fill: counting and volume (314.16)'),
    'final-exam-#4-065': ('B', 'Table 4, Chapter 9 What is the minimum size schedule 80 PVC conduit required for al...', 'Batch 3 N-M7 Conduit fill: conductor areas against the 40% column'),
    'final-exam-#4-066': ('B', 'Table 4, Chapter 9 How many #8 THW conductors can you install in a 1" rigid steel c...', 'Batch 3 N-M7 Conduit fill: conductor areas against the 40% column'),
    'final-exam-#4-067': ('B', 'Table 430.52(C)(1) What size branch circuit inverse time breaker is required for a...', 'Batch 3 N-M9 Motor circuit sizing by percentages (Article 430)'),
    'final-exam-#4-068': ('B', 'Table 4, Chapter 9 What is the maximum number of #6 XHHW conductors permitted in a...', 'Batch 3 N-M7 Conduit fill: conductor areas against the 40% column'),
    'final-exam-#4-069': ('B', 'Table 220.55 In an apartment building, what is the maximum demand for 28 - 8...', 'Batch 3 N-M8 Ranges, ovens and dryers: demand columns (Table 220.55, 220.54)'),
    'final-exam-#4-070': ('B', 'Table 430.250 The total load of a 15 hp, 208v, three-phase induction motor is...', 'Batch 3 N-M9 Motor circuit sizing by percentages (Article 430)'),
    'open-book-exam-#2-001': ('B', '408.43 Panelboards shall not be installed in the ___ position.', 'Batch 3 reuse ocpd_vertical_240-33'),
    'open-book-exam-#2-002': ('B', '210.7 Where two or more branch circuits supply devices or equipment on...', 'Batch 3 reuse multiwire_branch_circuit_210-4'),
    'open-book-exam-#2-004': ('B', '210.8(C) GFCI protection shall be provided for lighting outlets not excee...', 'Batch 3 repeat of final-exam-#3-006'),
    'open-book-exam-#2-007': ('A', '210.52(C)(1) Receptacle outlets shall be installed so that no point along the...', 'Batch 3 N-H4 Kitchen counter, bathroom and outdoor receptacles (210.52(B)-(E))'),
    'open-book-exam-#2-008': ('B', '590.4(J) For temporary holiday lighting, trees shall be permitted for sup...', 'Batch 3 repeat of final-exam-#1-016'),
    'open-book-exam-#2-009': ('A', '210.62 At least one 125 volt, single-phase, 15 or 20 amp rated receptac...', 'Batch 3 N-H5 Show window receptacles and load (210.62, 220.14(G))'),
    'open-book-exam-#2-011': ('B', '210.12(B) AFCI protection on all 120 volt, single-phase, 15 and 20 amp bra...', 'Batch 3 reuse afci_tr_dwelling_210-12_406-12'),
    'open-book-exam-#2-012': ('B', 'Table 310.16 What is the ampacity of a #12 THWN conductor installed in an amb...', 'Batch 3 repeat of final-exam-#1-014'),
    'open-book-exam-#2-013': ('B', '210.8(A)(2) A wall-mounted central vacuum assembly connected to a single rec...', 'Batch 3 repeat of final-exam-#1-012'),
    'open-book-exam-#2-015': ('A', '210.52(A)(2) In a dwelling bedroom, wall space includes any space ___ or more...', 'Batch 3 repeat of final-exam-#1-011'),
    'open-book-exam-#2-018': ('B', '220.14(H) The calculated load of a 12 foot length of fixed multioutlet ass...', 'Batch 3 repeat of final-exam-#1-010'),
    'open-book-exam-#2-022': ('B', '310.6(C) An acceptable color for ungrounded conductors is ___.', 'Batch 3 repeat of final-exam-#1-009'),
    'open-book-exam-#2-023': ('A', '680.62(E) All receptacles located within ___ of a therapeutic tub shall be...', 'Batch 3 N-H6 Therapeutic tub: GFCI zone around the tub (680.62(E))'),
    'open-book-exam-#2-025': ('A', '210.52(E)(3) Balconies, decks and porches that are within 4 inches horizontal...', 'Batch 3 repeat of final-exam-#1-008'),
    'open-book-exam-#3-001': ('A', '210.52(C)(3) As a general rule, receptacle outlets provided for the small app...', 'Batch 3 N-H4 Kitchen counter, bathroom and outdoor receptacles (210.52(B)-(E))'),
    'open-book-exam-#3-002': ('B', '240.21(B)(1) For a feeder tap not exceeding 10 feet in length and field insta...', 'Batch 3 repeat of final-exam-#1-032'),
    'open-book-exam-#3-003': ('B', '210.52(H) In dwelling units, hallways of ___ feet or more in length shall...', 'Batch 3 repeat of final-exam-#1-031'),
    'open-book-exam-#3-004': ('B', '210.8(A)(11) Where a 20 amp receptacle is installed in a residential laundry...', 'Batch 3 reuse gfci_locations_210-8'),
    'open-book-exam-#3-008': ('B', '408.5 Where conduits enter a floor-standing switchboard, switchgear, o...', 'Batch 3 repeat of final-exam-#1-029'),
    'open-book-exam-#3-009': ('B', '514.11(A) Fuel dispensing systems shall be provided with one or more clear...', 'Batch 3 repeat of final-exam-#1-028'),
    'open-book-exam-#3-010': ('B', 'Table 310.15(B)(1)(1) The ampacity of three #10 THWN-2 conductors installed in a racew...', 'Batch 3 repeat of final-exam-#1-027'),
    'open-book-exam-#3-011': ('B', 'Table 310.4(1) The conductor is marked RHW-2 on the insulation. What does the -...', 'Batch 3 repeat of final-exam-#1-026'),
    'open-book-exam-#3-012': ('B', '680.5(B) Outlets supplying all permanently installed nonsubmersible pump...', 'Batch 3 repeat of open-book-exam-#1-024'),
    'open-book-exam-#3-013': ('B', '630.12(A) For an arc welder with an I1max rating of 43 amps, what is the m...', 'Batch 3 repeat of final-exam-#1-025'),
    'open-book-exam-#3-015': ('B', '680.58 All 15 or 20 amp, single-phase, 125 volt through 250 volt recept...', 'Batch 3 repeat of final-exam-#1-024'),
    'open-book-exam-#3-016': ('B', '250.122(F)(1) Where ungrounded conductors are run in parallel in multiple race...', 'Batch 3 repeat of final-exam-#1-023'),
    'open-book-exam-#3-017': ('B', '210.52(G)(1) Where a dwelling has a two car attached garage, the Code require...', 'Batch 3 repeat of final-exam-#1-022'),
    'open-book-exam-#3-019': ('B', 'Table 220.55 The demand load for a 14 kW range installed in a dwelling unit i...', 'Batch 3 repeat of final-exam-#1-021'),
    'open-book-exam-#3-020': ('A', '250.53(A)(3) Where multiple driven ground rods are used to form the grounding...', 'Batch 3 repeat of final-exam-#1-020'),
    'open-book-exam-#3-021': ('A', '410.10(F) Luminaires installed in exposed or concealed locations under roo...', 'Batch 3 N-H8 Luminaire under metal roof decking (410.10(F))'),
    'open-book-exam-#5-001': ('A', '525.5(B)(2) Portable structures for fairs, carnivals and similar events shal...', 'Batch 3 N-H2 Portable fair structures near overhead power lines (525.5(B))'),
    'open-book-exam-#5-004': ('A', '110.26(E)(1)(c) ___ is permitted in the dedicated electrical space above a panel...', 'Batch 3 repeat of final-exam-#1-057'),
    'open-book-exam-#5-007': ('B', '409.102(B) The phase having the higher voltage to ground is ___, when an in...', 'Batch 3 reuse high_leg_marking_408-3f1'),
    'open-book-exam-#5-010': ('A', '300.4(D) Where an NM cable is installed parallel to framing members, the...', 'Batch 3 repeat of final-exam-#1-055'),
    'open-book-exam-#5-014': ('A', '225.18 Where overhead conductors not over 1,000 volts pass over the tra...', 'Batch 3 repeat of final-exam-#1-053'),
    'open-book-exam-#5-015': ('B', '550.32(F) Outdoor mobile home disconnecting means shall be installed so th...', 'Batch 3 repeat of final-exam-#1-052'),
    'open-book-exam-#5-016': ('B', '210.8(A) For dwelling units, GFCI protection shall be provided for person...', 'Batch 3 reuse gfci_locations_210-8'),
    'open-book-exam-#5-017': ('A', '110.26(C)(3) Personnel doors shall have listed panic hardware where equipment...', 'Batch 3 repeat of final-exam-#1-051'),
    'open-book-exam-#5-018': ('B', '800.44(B) Communications wires and cables and CATV type coaxial cables sha...', 'Batch 3 repeat of final-exam-#1-050'),
    'open-book-exam-#5-020': ('B', '300.5(J) Installation of direct buried cables in an area that is subject...', 'Batch 3 N-H7 Direct-buried conductors: emerging from grade and frost S-loops (300.5(D)(1), 300.5(J))'),
    'open-book-exam-#5-021': ('A', '250.52(A)(5) Grounding electrodes of pipe or conduit shall not be smaller tha...', 'Batch 3 N-H1 Driven electrodes: sizes and the three ways to install a rod'),
    'open-book-exam-#5-024': ('B', '352.30(A) PVC conduit shall be securely fastened within ___ of each outlet...', 'Batch 3 reuse supports_pvc_352-30'),
    'open-book-exam-#6-003': ('A', '250.52(A)(5) A copper-coated steel ground rod shall be at least ___.', 'Batch 3 N-H1 Driven electrodes: sizes and the three ways to install a rod'),
    'open-book-exam-#6-005': ('A', '225.18 Where overhead conductors not over 1,000 volts pass over a publi...', 'Batch 3 reuse overhead_clearances_225-18'),
    'open-book-exam-#6-006': ('A', '250.53(A)(4) Where a rock bottom is encountered, the ground rod shall be perm...', 'Batch 3 N-H1 Driven electrodes: sizes and the three ways to install a rod'),
    'open-book-exam-#6-008': ('A', '300.5(D)(1) Direct buried conductors emerging from grade shall be protected...', 'Batch 3 N-H7 Direct-buried conductors: emerging from grade and frost S-loops (300.5(D)(1), 300.5(J))'),
    'open-book-exam-#6-009': ('A', '430.102(B)(2) Where the controller disconnecting means for a motor is not in s...', 'Batch 3 reuse in_sight_disconnect_430-102_440-14'),
    'open-book-exam-#6-010': ('B', 'Table 430.250 What is the full load current of a 50 horsepower, three-phase, 4...', 'Batch 3 repeat of final-exam-#1-070'),
    'open-book-exam-#6-012': ('B', 'Table 250.122 What is the minimum size equipment grounding conductor for a 50...', 'Batch 3 repeat of final-exam-#1-068'),
    'open-book-exam-#6-014': ('B', 'Chapter 9, Note 4 Conduit nipples not over 24 inches in length may be filled to a...', 'Batch 3 repeat of final-exam-#1-067'),
    'open-book-exam-#6-016': ('B', 'Table 352.30(B) Rigid PVC, size 1 1/2 inch, shall be supported every ___.', 'Batch 3 reuse supports_pvc_352-30'),
    'open-book-exam-#6-018': ('B', '480.10(A) A battery room where batteries are being charged requires ventil...', 'Batch 3 repeat of final-exam-#3-060'),
    'open-book-exam-#6-022': ('B', '330.30(D)(2) Type MC cable shall be permitted to be unsupported and unsecured...', 'Batch 3 repeat of final-exam-#1-066'),
    'open-book-exam-#6-023': ('A', '680.11(A) Underground wiring within ___ horizontally from the inside wall...', 'Batch 3 repeat of final-exam-#1-060'),
    'open-book-exam-#6-024': ('B', '210.18 Branch circuits shall be rated in accordance with the ___.', 'Batch 3 repeat of final-exam-#1-059'),
    'open-book-exam-#9-012': ('B', '210.18 Branch circuits recognized by this article shall be rated in acc...', 'Batch 3 reuse branch_circuit_rating_210'),
    'open-book-exam-#9-016': ('B', '110.14(C)(2) Separately installed pressure connectors shall be used with cond...', 'Batch 3 repeat of open-book-exam-#7-017'),
    'open-book-exam-#9-018': ('B', '210.18 Where conductors of higher ampacity are used for any reason, the...', 'Batch 3 reuse branch_circuit_rating_210'),
    'open-book-exam-#11-001': ('A', '210.52(E)(3) Balconies, decks, and porches that are within ___ inches, horizo...', 'Batch 3 reuse balcony_receptacle_210-52e3'),
    'open-book-exam-#11-002': ('B', '408.7 Unused openings for circuit breakers and switches shall be close...', 'Batch 3 repeat of final-exam-#3-046'),
    'open-book-exam-#11-007': ('A', '250.194(A) Where metal fences are located within ___ feet of the exposed el...', 'Batch 3 N-H3 Metal fence bonding near exposed live parts (250.194(A))'),
    'open-book-exam-#11-009': ('B', '382.15(A) One or more nonmetallic extensions shall be permitted to run in...', 'Batch 3 repeat of final-exam-#5-049'),
    'open-book-exam-#11-020': ('A', '250.52(A)(4) A ground ring electrode shall be no smaller than ___ copper.', 'Batch 3 N-H1 Driven electrodes: sizes and the three ways to install a rod'),
    'open-book-exam-#11-021': ('B', '406.12 All nonlocking, 15 and 20 amp, 125-volt through 250-volt recepta...', 'Batch 3 reuse afci_tr_dwelling_210-12_406-12'),
    'open-book-exam-#11-022': ('A', '430.102(B) If locating a motors disconnecting means within sight of the mot...', 'Batch 3 reuse in_sight_disconnect_430-102_440-14'),
    'open-book-exam-#11-023': ('B', '314.16(B)(4) A three-way switch is counted as ___ conductor(s) based on the l...', 'Batch 3 N-M5 Box fill: counting and volume (314.16)'),
    'open-book-exam-#12-010': ('B', '110.15 On a 4-wire, delta-connected system where the midpoint of one ph...', 'Batch 3 reuse high_leg_marking_408-3f1'),
    'open-book-exam-#12-022': ('A', '358.30(A) Fastening of unbroken lengths of EMT conduit can be increased to...', 'Batch 3 repeat of final-exam-#3-013'),
    'open-book-exam-#12-023': ('B', '250.122(A) The minimum size copper equipment grounding conductor required o...', 'Batch 3 reuse egc_size_250-122'),
    'open-book-exam-#12-025': ('A', '225.18 Individual open conductors and cables other than service entranc...', 'Batch 3 reuse overhead_clearances_225-18'),
}
