"""Hand-written human explanation of what each question asks. Never states the answer."""

GISTS = {
    ("Final Exam #3", 28): "Vending machines, tire pumps, and water coolers are accessible to the general public. The question asks which of these public machines needs fast-trip protection for people.",
    ("Final Exam #5", 6): "A short length of armored cable at a terminal accommodates equipment movement and is exempt from securing. The question asks how long that free length may be.",

    ("Final Exam #1", 1): "Convert 60 percent to a fraction, then reduce to lowest terms. Percent means per hundred.",
    ("Final Exam #1", 2): "Some equipment requires rear or side access for field connections. The manufacturer must mark it where visible before the enclosure is opened. The question asks where that mark goes.",
    ("Final Exam #1", 3): "Service work requires a receptacle near the service equipment. In larger buildings the Code limits how far away it may be. The question asks what that limit is.",
    ("Final Exam #1", 4): "Office occupancies use a fixed volt-ampere value per square foot of floor area. The question hands you 5,000 square feet and says to skip the demand math. Multiply and pick the total.",
    ("Final Exam #1", 5): "With 0 volts across the switch and full voltage across the lamp, yet the lamp is dark: each reading narrows the fault location.",
    ("Final Exam #1", 6): "Seasonal decorative lighting requires evidence of testing. The question asks what proof the Code wants on the product.",
    ("Final Exam #1", 7): "Conductors inside switchgear operate at elevated temperature in restricted space. The question asks what quality the Code demands of those conductors.",
    ("Final Exam #1", 8): "A balcony, deck, or porch requires its own receptacle so no cord passes through a window or door. The question asks how high off the deck floor that outlet may sit.",
    ("Final Exam #1", 9): "Conductor insulation colors are restricted by function. The question asks which of these colors is permitted for ungrounded conductors.",
    ("Final Exam #1", 10): "A 12-foot multioutlet assembly in a commercial occupancy is not loaded simultaneously. The rule counts every 5 feet, or fraction of it, as one outlet. The question asks how many volt-amps that works out to.",
    ("Final Exam #1", 11): "Dwelling bedroom walls require receptacles at defined spacing, and only qualifying wall segments count toward it. The question asks how wide a stretch has to be before it counts.",
    ("Final Exam #1", 12): "An attached garage has a concrete floor exposed to moisture with occupants at ground potential. The question asks which fast-acting protection that vacuum outlet needs.",
    ("Final Exam #1", 13): "Three meters are wired three different ways around the load. Trace each meter's leads, then decide which hookup measures current.",
    ("Final Exam #1", 14): "Start from the table ampacity; no temperature correction applies at 86 degrees, then apply the adjustment factor for four current-carrying conductors. The question asks what you land on.",
    ("Final Exam #1", 15): "String lighting suspended overhead without a separate support wire must meet a minimum conductor size. The question asks the thinnest wire the Code allows there.",
    ("Final Exam #1", 16): "Vegetation moves with growth and wind, so outdoor wiring on trees requires flexible attachment means. The question asks what that hardware is called.",
    ("Final Exam #1", 17): "Overcurrent devices are manufactured in standard ratings, and circuits are designated accordingly. The question asks which of these lists is the true standard set.",
    ("Final Exam #1", 18): "An elevator motor draws high current briefly and then rests, unlike continuous-duty loads. The question asks what the Code calls that kind of work cycle.",
    ("Final Exam #1", 19): "Power in watts is the product of volts and a second quantity represented by the letter I. The question asks what I stands for.",
    ("Final Exam #1", 20): "Two ground rods installed too close together function as a single electrode. The question asks how far apart they must stand so both actually work.",
    ("Final Exam #1", 21): "A household range never operates at full calculated load, so the Code permits a demand factor. The question asks what a 14 kW range counts as.",
    ("Final Exam #1", 22): "A residential garage requires receptacle outlets for tools and equipment. The question asks the smallest number of outlets the Code demands in it.",
    ("Final Exam #1", 23): "Parallel feeder sets run in separate raceways, and each raceway requires its own equipment grounding path. The question asks how the ground wire must be run through them.",
    ("Final Exam #1", 24): "A fountain places water and people together, so nearby receptacles require ground-fault protection. The question asks how far from the water's edge that rule reaches.",
    ("Final Exam #1", 25): "A welder draws high current intermittently, so its overcurrent protection is sized above the nameplate rating. The question asks the biggest breaker allowed for a 43-amp welder.",
    ("Final Exam #1", 26): "Conductor surface markings identify its construction and ratings. The question asks what the dash-2 at the end of RHW-2 means.",
    ("Final Exam #1", 27): "Elevated ambient temperature reduces conductor ampacity; apply the temperature correction factor to the table value. Three of these wires at 112 degrees. The question asks what each one is still good for.",
    ("Final Exam #1", 28): "Fuel dispensing areas require an emergency shutoff that is reachable during a fire yet positioned away from the hazard. Twenty feet is given as the near limit. The question asks the far limit.",
    ("Final Exam #1", 29): "Raceways entering the bottom of floor-standing equipment cannot extend so far inside that they interfere with internal components. The question asks how many inches above the bottom they may rise.",
    ("Final Exam #1", 30): "A thermostat may serve as the disconnect only with a maintained OFF position requiring manual reset. The question asks what the Code demands of that switch.",
    ("Final Exam #1", 31): "A hallway without a receptacle invites cord-connected loads across the walking path. The question asks how long a hallway must be before it earns its own outlet.",
    ("Final Exam #1", 32): "A small tap conductor off a larger feeder has no overcurrent protection of its own, so the Code limits the rating of the upstream feeder overcurrent device. A 40-amp tap is given. The question asks that cap.",
    ("Final Exam #1", 33): "A hallway switch and a stair switch controlling one luminaire each require three terminals. The question asks which standard switch type that is.",
    ("Final Exam #1", 34): "Outdoor flexible cords require weather-resistant construction identified by their type letters. The question asks which of these four types is rated for wet and sunny.",
    ("Final Exam #1", 35): "A structural steel column in contact with earth may serve as an electrode only with sufficient earth contact. The question asks how many feet must be in the earth.",
    ("Final Exam #1", 36): "A dwelling service is not loaded to full rating, so service conductors may be sized below the service rating within limits. The question asks what share of the rating they may be.",
    ("Final Exam #1", 37): "Cable trays must not propagate fire along their length. The question asks what the tray itself must be made of.",
    ("Final Exam #1", 38): "Type UF cable is rated for wet, dry, and corrosive soil conditions. The question asks where the Code lets you run it, and three of these answers are places it forbids.",
    ("Final Exam #1", 39): "A controller serving a motor group must display a marking identifying its protection. The question asks which word the Code requires in that marking.",
    ("Final Exam #1", 40): "Multiple household dryers do not operate simultaneously, so a demand factor applies. The question asks what share five of them count as.",
    ("Final Exam #1", 41): "A motor stop device must directly open the control circuit, which requires a specific wiring configuration. The question asks which way.",
    ("Final Exam #1", 42): "Outdoor receptacles exposed to weather require wet-location construction; several similar designations exist. The question asks which exact one the Code wants.",
    ("Final Exam #1", 43): "A paddle fan installed over a hot tub without ground-fault protection must meet a minimum mounting height above the water. The question asks the minimum height.",
    ("Final Exam #1", 44): "An unintentional connection between an ungrounded conductor and metal that is not meant to carry current has a specific defined term. The question describes exactly that and asks the name.",
    ("Final Exam #1", 45): "A waste-disposer cord in a damp location under strain has both minimum and maximum length limits. Eighteen inches is given as the minimum. The question asks the long end.",
    ("Final Exam #1", 46): "Convert 40 percent to a fraction and reduce to lowest terms.",
    ("Final Exam #1", 47): "Four switch contacts, each with a different symbol drawn under the blade. The question asks which symbol stands for a thermal (temperature) element.",
    ("Final Exam #1", 48): "A 15-ampere hallway receptacle in a dwelling must meet child-protection construction requirements. The question asks which protection that outlet needs.",
    ("Final Exam #1", 49): "Concrete cover over a trench provides mechanical protection, reducing the required earth cover beneath it. The question asks how much cover still stays required.",
    ("Final Exam #1", 50): "Communications conductors crossing over a roof must maintain clearance above the roof surface. The question asks that minimum height.",
    ("Final Exam #1", 51): "Large energized equipment requires door hardware that permits immediate egress without special operation. The question asks how close a door must be before it needs that hardware.",
    ("Final Exam #1", 52): "An outdoor disconnect enclosure must be mounted with its bottom above moisture exposure and physical damage. The question asks the minimum height of the box bottom.",
    ("Final Exam #1", 53): "Railroad tracks carry tall rolling stock, so overhead conductors require substantial clearance. The question asks the minimum clearance over the rails.",
    ("Final Exam #1", 54): "Flexible cord splices are generally prohibited, with repair permitted only for specified hard-service cord types. The question asks which other cord type the Code also names for repair.",
    ("Final Exam #1", 55): "Fasteners can penetrate cables secured flat against framing, so the Code requires a setback from the framing edge. The question asks that setback distance.",
    ("Final Exam #1", 56): "A receptacle supplying a small motor without integral overload protection is limited in rating so a stalled motor cannot overheat the cord. The question asks the biggest outlet allowed there.",
    ("Final Exam #1", 57): "The dedicated space above electrical equipment must remain clear of foreign systems. The question asks which one may share that space.",
    ("Final Exam #1", 58): "A transformer nameplate carries its ratings; most listed items belong there. The question asks which one does not.",
    ("Final Exam #1", 59): "A branch circuit's rating is determined by a single element — not its conductors or outlets. The question asks what gives the circuit its rating.",
    ("Final Exam #1", 60): "Underground wiring near a pool must maintain horizontal separation so fault current cannot reach the water. The question asks how far out that zone goes.",
    ("Final Exam #1", 61): "Gases, dusts, and fibers are assigned separate hazardous-location classes. The question describes fibers and flyings and asks which class that is.",
    ("Final Exam #1", 62): "A 10-volt difference exists between the panel and the load. The question asks what share of the starting 125 volts that loss is. Divide volts lost by source volts.",
    ("Final Exam #1", 63): "The drawing scale equates one-quarter inch to one foot. The question asks how long three and a half paper inches really is.",
    ("Final Exam #1", 64): "Construction drawings are reviewed in a standard sequence. The question asks where you start.",
    ("Final Exam #1", 65): "Alternating current reverses 60 times per second; the question covers one quarter-cycle. Compute the duration of one quarter-cycle.",
    ("Final Exam #1", 66): "A short length of flexible raceway serving a luminaire is exempt from standard support intervals. The question asks how long that free length may be.",
    ("Final Exam #1", 67): "A short conduit section between enclosures permits a higher fill percentage than a complete conduit run. The question asks how full, as a percent.",
    ("Final Exam #1", 68): "The equipment grounding conductor is selected from its table using the upstream overcurrent device rating. A 50-amp breaker is given. The question asks the copper size across from it.",
    ("Final Exam #1", 69): "A wooden sign enclosure near hot lampholders is combustible and must maintain separation. The question asks how far back the wood must stay.",
    ("Final Exam #1", 70): "Motor current comes from the Code's own table, never the nameplate, and a 480-volt system uses the 460-volt column. The question asks what a 50-horse wound-rotor motor reads there.",
    ("Open Book Exam #1", 7): "Conductors passing through sections they do not terminate in create hazards. Only conductors terminating in a section may occupy it. The question asks which kind of section a wire must end in to sit there.",
    ("Open Book Exam #1", 1): "Opening only part of the circuit leaves the neutral energized from the other side. The question asks which wires the disconnect must open together.",
    ("Open Book Exam #1", 2): "At the service equipment, the neutral and ground systems connect at exactly one location. The question asks the name of that link.",
    ("Open Book Exam #1", 3): "Floor area for load math is measured wall to wall, and it matters which face of the wall you use. The question asks which side you measure from.",
    ("Open Book Exam #1", 4): "A notch in a stud leaves the cable nearly exposed to drywall screws, so a steel plate guards it. The question asks how thick that plate must be.",
    ("Open Book Exam #1", 5): "Motor control center servicing requires nearby power for test equipment. The question asks how close that outlet must be.",
    ("Open Book Exam #1", 6): "A snap switch interrupting motor or ballast loads is subject to arcing and is limited below its lamp rating. The question asks what share of its rating it may switch.",
    ("Open Book Exam #1", 8): "A plate electrode is effective only in permanently moist earth at sufficient depth. The question asks how deep it must be buried.",
    ("Open Book Exam #1", 9): "Each grounded conductor requires its own terminal, with no doubling under one screw. The question asks how the Code says each one must land.",
    ("Open Book Exam #1", 10): "Receptacles near a bathtub combine water and electricity access. The question asks how far from the tub edge the protection reaches.",
    ("Open Book Exam #1", 11): "An open panelboard exposes energized parts to passersby. The question asks what the working space requires during servicing.",
    ("Open Book Exam #1", 12): "A commercial kitchen is a wet environment with grounded surfaces and public occupancy. The question asks which fixture triggers the protection rule there.",
    ("Open Book Exam #1", 13): "Load calculations do not require extended decimal precision. The question asks how small a fraction you may simply drop.",
    ("Open Book Exam #1", 14): "A crawl space is a damp, restricted area; luminaires there still require ground-fault protection. The question asks the voltage limit of that rule.",
    ("Open Book Exam #1", 15): "Equipment with rear field connections must carry a marking visible before access. The question asks where the factory mark goes.",
    ("Open Book Exam #1", 16): "Test equipment requires a receptacle near service equipment. The question asks the distance limit for that outlet.",
    ("Open Book Exam #1", 17): "Conductors inside switchgear operate at elevated temperatures in confined space. The question asks what quality the Code demands of them.",
    ("Open Book Exam #1", 18): "Certain outdoor receptacles serve only maintenance equipment. The question asks which kind of outlet the rule covers.",
    ("Open Book Exam #1", 19): "A bare lamp on a construction site is exposed to physical damage. The question asks what the Code names as the required protection.",
    ("Open Book Exam #1", 20): "A laundry area requires a dedicated circuit serving no other loads. The question asks what size breaker feeds it.",
    ("Open Book Exam #1", 21): "Office occupancies use a fixed volt-ampere value per square foot. Five thousand square feet, no demand math. Multiply and pick the total.",
    ("Open Book Exam #1", 22): "The laundry receptacle must be located near the equipment it serves. The question asks the maximum distance allowed.",
    ("Open Book Exam #1", 23): "Seasonal decorative lighting requires evidence of testing. The question asks what proof the Code wants on the product.",
    ("Open Book Exam #1", 24): "Pool pump motors operate adjacent to water across a range of current ratings. The question asks up to what amperage the fast-trip rule reaches.",
    ("Open Book Exam #1", 25): "The disconnect must satisfy both visibility and accessibility conditions. The question asks how reachable that disconnect must be.",
    ("Open Book Exam #4", 1): "Only a trained worker capable of recognizing the hazards involved may access live equipment. The question describes that worker and asks what the Code calls them.",
    ("Open Book Exam #4", 2): "Dwelling outdoor receptacles require ground-fault protection within a defined overcurrent range. The question asks where that cutoff sits.",
    ("Open Book Exam #4", 3): "Type NM cable is limited to dry interior locations. Three of these places welcome it. The question asks which place forbids it.",
    ("Open Book Exam #4", 4): "Concrete above a trench provides protection that reduces the required earth cover beneath it. The question asks how much cover still stays required.",
    ("Open Book Exam #4", 5): "A 15-ampere hallway receptacle in a dwelling must meet child-protection construction requirements. The question asks what that outlet needs.",
    ("Open Book Exam #4", 6): "A waste-disposer cord operates in damp conditions under strain, so the Code limits its length at both ends. Eighteen inches is given as the short end. The question asks the long end.",
    ("Open Book Exam #4", 7): "An isolated-ground receptacle for sensitive equipment must be visibly identifiable. The question asks what mark sits on its face.",
    ("Open Book Exam #4", 8): "In a multiwire circuit, all conductors must originate from the same equipment. The question asks what that equipment must contain.",
    ("Open Book Exam #4", 9): "An unintentional connection between an ungrounded conductor and metal that is not meant to carry current has a specific defined term. The question describes exactly that and asks the name.",
    ("Open Book Exam #4", 10): "Seasonal lots are temporary installations with their own splicing rules. The question asks whether a box is optional or mandatory.",
    ("Open Book Exam #4", 11): "A fan over a hot tub without ground-fault protection must maintain height above occupants. The question asks the minimum height.",
    ("Open Book Exam #4", 12): "Arc-fault protection has a defined coverage scope along the circuit. The question asks what exactly gets that protection.",
    ("Open Book Exam #4", 13): "A mark from a testing laboratory shows the equipment was evaluated. The question describes that mark and asks what it is called.",
    ("Open Book Exam #4", 14): "Outdoor receptacles exposed to weather require wet-location construction; several similar designations exist. The question asks which exact one the Code wants.",
    ("Open Book Exam #4", 15): "Multiple dryers in a single building do not operate simultaneously, so a demand factor applies. The question asks what share five of them count as.",
    ("Open Book Exam #4", 16): "A controller serving a motor group must display a marking identifying its protection. The question asks which word the Code requires in that marking.",
    ("Open Book Exam #4", 17): "Type UF cable is rated for wet, dry, and corrosive soil. The question asks where it may run, and three answers are places it forbids.",
    ("Open Book Exam #4", 18): "Type NM cable may enter surface enclosures through short lengths of protective raceway. The question asks the shortest those sleeves may be.",
    ("Open Book Exam #4", 19): "A luminaire supported by an outlet box is limited to 6 lb and requires minimum-size screws. The question asks the smallest screw size permitted.",
    ("Open Book Exam #4", 20): "Cable trays must resist flame propagation. The question asks what the tray itself must be made of.",
    ("Open Book Exam #4", 21): "Snow-melting equipment requires a dedicated receptacle; the rule turns on how reachable it must be. The question asks which word fills the blank.",
    ("Open Book Exam #4", 22): "A dwelling service is not fully loaded, so its conductors may be sized below the service rating. The question asks what share of the rating they may be.",
    ("Open Book Exam #4", 23): "Arc-fault protection is required in most dwelling living areas. Three of these rooms need it. The question asks which one does not.",
    ("Open Book Exam #4", 24): "A structural steel column may serve as an electrode only with sufficient earth contact. The question asks how many feet must be buried.",
    ("Open Book Exam #4", 25): "Outdoor flexible cords require weather-resistant construction identified by their type letters. The question asks which of these four types is rated for wet and sunny.",
    ("Open Book Exam #7", 1): "Neutral current requires a continuous conductive path back to the source. The question asks which word describes how that joining must be made.",
    ("Open Book Exam #7", 2): "Copper conductor resistance values are tabulated in Chapter 9. The question asks which table holds it.",
    ("Open Book Exam #7", 3): "Equipment serviced while energized requires arc-flash labeling, with limited exceptions. The question asks which place is exempt.",
    ("Open Book Exam #7", 4): "X-ray equipment operates in brief high-current pulses, so conductors follow the pulse-based rating rather than the continuous one. The question asks which demand rating that is.",
    ("Open Book Exam #7", 5): "Floodplain measurements reference how high water can rise before spilling over. The question asks the name of that level.",
    ("Open Book Exam #7", 6): "A field-assembled extension cord must use conductors sized for the circuit rating. The question asks the smallest wire size allowed.",
    ("Open Book Exam #7", 7): "Two overcurrent devices in series coordinate only with no other connections between them. The question asks what must not be connected alongside the downstream one.",
    ("Open Book Exam #7", 8): "Ventilated equipment requires unobstructed airflow. The question asks what kind of openings trigger that rule.",
    ("Open Book Exam #7", 9): "Service equipment must be rated not less than the total computed load. The question asks which load value sets its minimum size.",
    ("Open Book Exam #7", 10): "A heated ceiling subjects overlying wiring to elevated temperature. The question asks how far above it wiring must run.",
    ("Open Book Exam #7", 11): "Multi-outlet tool circuits require conductors rated at least for the branch-circuit protection. The question asks the exact Code wording for that minimum.",
    ("Open Book Exam #7", 12): "Thin paint-type coatings do not qualify as outdoor corrosion protection. The question asks which coating is indoor-only.",
    ("Open Book Exam #7", 13): "Burial depths live in one specific table. The question asks which table number holds them.",
    ("Open Book Exam #7", 14): "Conduit size names live in one specific table. The question asks which table number holds them.",
    ("Open Book Exam #7", 15): "Conductors may start from their own temperature rating, but the lowest temperature rating in the chain caps the final ampacity. The question asks what that link is called.",
    ("Open Book Exam #7", 16): "During normal power loss, occupants must locate the emergency supply. The sign at the entrance names its type plus one more fact. The question asks what that fact is.",
    ("Open Book Exam #7", 17): "Terminations are rated for a temperature that limits conductor selection. The question asks which word describes that published rating.",
    ("Open Book Exam #7", 18): "The dwelling's required branch-circuit count is the total computed load divided by the circuit rating. The question asks which word fills that blank.",
    ("Open Book Exam #7", 19): "Foreign materials inside a panel are prohibited, and one listed contaminant causes corrosion. The question asks which one the Code names.",
    ("Open Book Exam #7", 20): "One part of a sign provides weather protection without containing electrical components. The question asks what that part is called.",
    ("Open Book Exam #7", 21): "A transformer changes the voltage level, and overcurrent protection is required on a specific side. The question asks which side.",
    ("Open Book Exam #7", 22): "Open equipment doors must not block egress; the passage width has a minimum. The question asks how many inches wide.",
    ("Open Book Exam #7", 23): "High-voltage flexible cable terminations are restricted to qualified personnel. The question asks which cable type the rule covers.",
    ("Open Book Exam #7", 24): "One 4-wire system includes a high leg with elevated voltage to ground, requiring identification. The question asks what that system is called.",
    ("Open Book Exam #7", 25): "A building with multiple supplies must document all sources at every shutoff point. The question asks where that plaque goes.",
    ("Open Book Exam #10", 1): "Agricultural buildings contain dust that can enter motor enclosures. The question asks what the motor construction must exclude.",
    ("Open Book Exam #10", 2): "Porches, garages, and unfinished spaces are excluded from habitable-area load calculations. The question asks which of these stays out.",
    ("Open Book Exam #10", 3): "The green screw accepts exactly one conductor. The question asks which conductor that is.",
    ("Open Book Exam #10", 4): "Conductors leaving an industrial panel fall into two classifications, each with its own rules. The question asks which one these supply wires count as.",
    ("Open Book Exam #10", 5): "Buried raceways corrode from aggressive backfill. The question asks what harmful backfill causes.",
    ("Open Book Exam #10", 6): "A device that opens a remote disconnect through a control relay has a defined term. The question describes it and asks the name.",
    ("Open Book Exam #10", 7): "Three of these statements reflect Code requirements. The question asks which one is false, so read each like its own true-or-false quiz.",
    ("Open Book Exam #10", 8): "A cable tray containing welder conductors must be marked to prevent adding incompatible wiring. The question asks what the sign must say.",
    ("Open Book Exam #10", 9): "An amusement ride has exactly one person responsible for starting, stopping, and controlling it. The question asks what the Code calls that person.",
    ("Open Book Exam #10", 10): "Conductors near a loading dock door must maintain side clearance and never run beneath the opening. Two rules, and both must hold. The question asks which installation obeys both.",
    ("Open Book Exam #10", 11): "A rooftop antenna is frequently the highest metal structure, so separation from power conductors is required above a voltage threshold. The question asks above what voltage the power lines must be kept away from it.",
    ("Open Book Exam #10", 12): "Control circuits use relaxed rules only within voltage and power limits. Thirty volts is given. The question asks the volt-amp cap.",
    ("Open Book Exam #10", 13): "A box carried only by its two conduit entries is exempt from separate support given compliant joints. The question asks how those conduits must connect.",
    ("Open Book Exam #10", 14): "Small-gauge X-ray control conductors require low-rated overcurrent protection. The question asks the biggest breaker allowed.",
    ("Open Book Exam #10", 15): "Copper-clad aluminum conductors require a minimum copper percentage. The question asks the minimum percent copper.",
    ("Open Book Exam #10", 16): "With a concrete wall opposite the equipment, the required working depth changes. The question asks what concrete counts as.",
    ("Open Book Exam #10", 17): "Gases, dusts, and fibers are assigned separate hazardous-location classes. The question describes fibers and flyings and asks which class that is.",
    ("Open Book Exam #10", 18): "An isolated-ground receptacle bears an identification mark on its face. The question asks what that mark is.",
    ("Open Book Exam #10", 19): "A hospital bed location serves critical equipment requiring dedicated, reliable receptacles. The question asks the minimum outlets at each bed spot.",
    ("Open Book Exam #10", 20): "A deck requires its own accessible receptacle within a maximum height. The question asks the maximum height above the deck floor.",
    ("Open Book Exam #10", 21): "Fire pump equipment must be elevated above potential standing water. The question asks how many inches up.",
    ("Open Book Exam #10", 22): "Two voltage levels in one raceway require cable with suitable separation construction. The question asks which insulation type the rule covers.",
    ("Open Book Exam #10", 23): "Recreational-vehicle sites predominantly require 30-ampere receptacles. The question asks what percent of sites must have it.",
    ("Open Book Exam #10", 24): "The conductor joining the system neutral to earth has a defined term. The question asks what it is.",
    ("Open Book Exam #10", 25): "High-voltage raceways require clean backfill; unsuitable material damages the raceway. The question asks what that fill can do to the raceway.",
    ("Final Exam #3", 1): "Cover plates with a built-in night light or USB charger contain their own low-power circuitry and must be listed. The question asks what kind of output connector the rule names.",
    ("Final Exam #3", 2): "An RV feeder from a 208Y/120-volt, 3-phase system can carry several kinds of conductors. The question asks which of the three listed items the feeder may include.",
    ("Final Exam #3", 3): "Large industrial process heaters are split into subdivided loads, each with its own supplementary fuses. The question asks what the Code calls the conductors feeding those fuses.",
    ("Final Exam #3", 4): "Cable tray normally holds only the wiring methods its article lists, but airports get a special allowance for series-circuit airfield lighting fed by constant current regulators, where only qualified people touch it. The question asks the highest cable voltage rating that allowance covers.",
    ("Final Exam #3", 5): "Low-voltage fixed heating runs from an isolating power unit whose output is capped for shock safety. The question asks the peak AC voltage limit, not the RMS value.",
    ("Final Exam #3", 6): "Crawl spaces are damp and put people close to the earth, so lighting outlets there need ground-fault protection up to a set voltage. The question asks that voltage.",
    ("Final Exam #3", 7): "Portable and storable immersion pools bring water close to plug-in audio gear. The question asks how far from the pool walls the grounding and GFCI rule reaches.",
    ("Final Exam #3", 8): "Combustible fibers are classified by how they are handled: being manufactured or processed is one division, simply stored or handled is another. The question asks which classification applies to storage and handling.",
    ("Final Exam #3", 9): "Part IX of the motor article covers disconnecting means for motor circuits. The question asks what that disconnect must separate from the circuit.",
    ("Final Exam #3", 10): "Some Article 100 definitions carry an article number in parentheses, which limits where that definition applies. The question asks how far the busbar definition reaches.",
    ("Final Exam #3", 11): "Electrical safety training stresses where incidents usually begin: equipment, procedures, enforcement, or human action. The question asks which one starts most of them.",
    ("Final Exam #3", 12): "Standards writers, trade associations, and testing laboratories play different roles. The question asks which organization actually tests equipment and keeps records of what it tested.",
    ("Final Exam #3", 13): "EMT normally must be fastened within 3 feet of each termination, but an exception stretches that where framing gets in the way. The question asks how far the exception allows.",
    ("Final Exam #3", 14): "A receptacle on a circuit rated higher than itself has a cap on the cord-and-plug load it may carry. The question asks that cap for a 15-amp receptacle on a 20-amp multi-outlet circuit.",
    ("Final Exam #3", 15): "Overcurrent device enclosures have a required mounting orientation, with exceptions only where that is impracticable. The question asks which orientation is required.",
    ("Final Exam #3", 16): "Conductor temperature depends partly on heat generated by the load current itself, and the rule names two components of that current. The question asks the one besides the fundamental.",
    ("Final Exam #3", 17): "For small circuits, the minimum equipment grounding conductor from the sizing table matches the usual circuit wire size. The question asks which of these circuit ratings that is true for.",
    ("Final Exam #3", 18): "Room air conditioners may be cord-connected, and the maximum cord length depends on the voltage rating. The question asks the limit at 120 volts.",
    ("Final Exam #3", 19): "Anyone working on a motor or its driven machinery must be able to see the device that kills its power. The question asks which device must be in sight of both.",
    ("Final Exam #3", 20): "Antenna lead-ins must stay clear of open power conductors to prevent accidental contact. The question asks the minimum clearance when the power conductors are under 250 volts and closeness cannot be avoided.",
    ("Final Exam #3", 21): "Electrical safe work practices start from an assessment of the hazard a worker faces. The question asks what that assessment, and so the practices, are based on.",
    ("Final Exam #3", 22): "Tools for energized work must be made and marked for it, not just have plastic grips. The question asks what marking identifies a proper insulated screwdriver.",
    ("Final Exam #3", 23): "Amusement attractions use small control wiring, and unjacketed ribbon cable gets a stricter minimum size than jacketed cable. The question asks that minimum AWG size.",
    ("Final Exam #3", 24): "A building fed by only a couple of 2-wire branch circuits still needs a disconnect of some minimum rating. The question asks that minimum rating in amps.",
    ("Final Exam #3", 25): "Supplementary overcurrent devices add protection inside equipment but are not the required branch-circuit protection. The question asks which statement about them is true.",
    ("Final Exam #3", 27): "A grounding electrode conductor that runs only to a concrete-encased electrode has a size cap, no matter how big the service is. The question asks the largest copper size ever required there.",
    ("Final Exam #3", 29): "When a fault occurs, the ideal is that only the nearest protective device opens and the rest of the system stays on. The question asks the defined term for that design choice.",
    ("Final Exam #3", 30): "Motor control circuit terminals on small copper wire have a minimum tightening torque unless the device is marked otherwise. The question asks that minimum in pound-inches.",
    ("Final Exam #3", 31): "Overhead communications wires entering a building have several rules about their position relative to power wires and roofs. The question asks which of the listed requirements apply.",
    ("Final Exam #3", 32): "The Code defines a nursing home partly by how many round-the-clock inpatients it cares for. The question asks the minimum number in that definition.",
    ("Final Exam #3", 33): "Power equals voltage times current, so current is power divided by voltage. The question gives watts and volts and asks for the current.",
    ("Final Exam #3", 34): "Boxes that hold a device on small conductors must be deep enough for the device and the wire behind it. The question asks the minimum depth.",
    ("Final Exam #3", 35): "Dwelling receptacles for specific appliances like washers and ranges must be close to where the appliance will sit. The question asks how close.",
    ("Final Exam #3", 36): "Cords supplied with a listed appliance or luminaire are protected differently from ordinary flexible cord. The question asks the condition under which they count as protected.",
    ("Final Exam #3", 37): "Nonmetallic underground conduit with conductors (NUCC) comes with conductors already inside, so the conduit has to be cut back at the ends. The question asks what activity requires that trimming.",
    ("Final Exam #3", 38): "A motor briefly draws much more current than its running load, and the short-circuit and ground-fault device must not trip on that. The question asks which current it must carry.",
    ("Final Exam #3", 39): "A furnace or boiler must not lose power because some other load tripped a shared circuit. The question asks what kind of branch circuit central heating equipment needs.",
    ("Final Exam #3", 40): "Resistance welder supply conductors are sized from the primary current times a multiplier from the duty-cycle table. The question gives a 15 percent duty cycle and 21 amps and asks the resulting ampacity.",
    ("Final Exam #3", 41): "Lockout/tagout depends on knowing every energy source and making sure each worker controls them. The question asks what must be in place before the lockout is applied.",
    ("Final Exam #3", 42): "A cord-and-plug appliance can use its own plug and receptacle as the disconnect, if people can reach it. The question asks the access level the Code requires for that connector.",
    ("Final Exam #3", 43): "Electricity itself cannot be seen, so workers rely on indirect evidence that a hazard is present. The question asks how a hazard is recognized.",
    ("Final Exam #3", 44): "Sensitive electronic equipment on separately derived 120-volt systems has tighter voltage-drop limits than ordinary wiring. The question asks the limit for branch circuits alone.",
    ("Final Exam #3", 45): "AC waveforms are described by several terms, and one of them counts the complete cycles in each second. The question asks which term that is.",
    ("Final Exam #3", 46): "An empty breaker space leaves a hole into live parts. The question asks what the opening must be closed with.",
    ("Final Exam #3", 47): "Service-entrance cable normally ends in a listed service head, but an exception lets Type SE cable be bent into a shape and taped instead. The question asks what that shape is called.",
    ("Final Exam #3", 48): "Trade size 3/8 flexible metal conduit has its own fill table because it is too small for the Chapter 9 tables. The question asks the largest THHN size that table allows.",
    ("Final Exam #3", 49): "Equipment that needs servicing must have a receptacle close enough for a worker's tools. The question asks the maximum distance from that equipment.",
    ("Final Exam #3", 50): "A water pipe used as an electrode must stay bonded even when a meter or other equipment is removed for repair. The question asks what property the bonding jumper needs to allow that.",
    ("Final Exam #3", 51): "A mobile home's outdoor disconnect must be mounted high enough off the ground to stay clear of water and grade. The question asks the minimum height to the bottom of the enclosure.",
    ("Final Exam #3", 52): "Motor overload devices go in specific conductors, and the count depends on the motor and supply type. The question asks how many a three-phase motor needs.",
    ("Final Exam #3", 53): "Rigid metal conduit made up with threaded couplings is stiff enough to span farther between supports, with the distance set by trade size. The question asks the allowed spacing for 1-inch conduit.",
    ("Final Exam #3", 54): "Cut ends of flexible metal conduit must be finished so rough edges do not damage wire, except with certain fittings. The question asks which fittings make trimming unnecessary.",
    ("Final Exam #3", 55): "Equal resistors in parallel share current, so the total resistance is lower than either one. The question asks the total for two equal 2,000-ohm resistors.",
    ("Final Exam #3", 56): "A building served by a single branch circuit for limited loads still needs a disconnect of some minimum rating. The question asks that minimum.",
    ("Final Exam #3", 57): "When derating for crowded raceways, only some conductors count as current-carrying. The question asks how the grounding conductor is treated in that count.",
    ("Final Exam #3", 58): "Terms used in more than one article are defined in the general definitions article, not in the hazardous-location articles. The question asks where the ignitible fibers/flyings definition lives.",
    ("Final Exam #3", 59): "Pool pump receptacles must sit a set distance back from the water. The question asks the minimum distance from the inside pool walls.",
    ("Final Exam #3", 60): "Batteries can release gases that are dangerous if they build up in a room. The question asks what kind of mixture the ventilation rule is meant to prevent.",
    ("Final Exam #3", 61): "Motor terminal housings enclose live connections and must be sturdy. The question asks what the housings must be made of.",
    ("Final Exam #3", 62): "Electrical drawings use short standard abbreviations for common terms. The question asks which abbreviation stands for power.",
    ("Final Exam #3", 63): "Bare copper busbars in an unventilated enclosure are rated by amps per square inch of cross-section. The question asks the continuous rating of a 1 1/2 square inch bar.",
    ("Final Exam #3", 64): "Dwelling GFCI rules list many locations where 125-volt receptacles need protection. The question asks which of the listed locations are covered.",
    ("Final Exam #3", 65): "The single-phase dwelling service table lets conductors be sized at a reduced percentage, but only for certain services. The question asks which services may use it.",
    ("Final Exam #3", 66): "Concrete-encased electrodes normally must join the grounding electrode system, but there is relief where the rebar cannot be reached without breaking concrete. The question asks which buildings get that relief.",
    ("Final Exam #3", 67): "Cord-and-plug connected air conditioners are limited in plug and receptacle rating, with one limit at 125 volts and another at 250 volts. The question asks the 250-volt limit.",
    ("Final Exam #3", 68): "With several elevator machines in one room, each disconnect must be clearly matched to what it shuts off. The question asks what the disconnect numbers must correspond to.",
    ("Final Exam #3", 69): "A feeder to a group of motors is protected based on the biggest motor's branch-circuit protective device plus the other motors' full-load currents. The question asks how the feeder device relates to that largest device.",
    ("Final Exam #3", 70): "Generator symbols show how the windings are connected by drawing a shape inside a circle. The question asks what shape marks a delta-wound machine.",
    ("Final Exam #5", 1): "FCC flat cable lies under carpet squares, which must come up easily for access. The question asks how carpet squares that are fastened down must be attached.",
    ("Final Exam #5", 2): "Armored cable buried in thermal insulation must use high-temperature conductors, even though its ampacity is limited to a lower column. The question asks the required conductor rating.",
    ("Final Exam #5", 3): "Several cable types are defined by their outer covering. The question describes an interlocking tape or smooth or corrugated metal armor and asks which type that is.",
    ("Final Exam #5", 4): "Flat conductor cable under carpet has to connect to ordinary wiring somewhere. The question asks what device those power, grounding, and shield connections must be made in.",
    ("Final Exam #5", 5): "Flat cable assemblies are tapped with devices that clip onto the conductors, and those devices have minimum and maximum ratings. The question asks the minimum ampere rating.",
    ("Final Exam #5", 7): "FCC flat cable has several defined layers above and below it. The question asks the name of the protective layer between the floor and the cable.",
    ("Final Exam #5", 8): "MC cable conductors have different minimum sizes for power circuits and for control and signal circuits. The question asks the smallest copper size allowed at all.",
    ("Final Exam #5", 17): "MI cable is a mineral-insulated, metal-sheathed cable with a wide list of permitted uses. The question asks which statement about it is true.",
    ("Final Exam #5", 18): "UF cable's ampacity comes from a single temperature column in the conductor tables, regardless of its insulation markings. The question asks which column.",
    ("Final Exam #5", 19): "Nonmetallic-sheathed cable comes in versions for dry and for damp or corrosive locations, and they have different jacket requirements. The question asks which type needs the flame, moisture, fungus, and corrosion-resistant covering.",
    ("Final Exam #5", 20): "MI cable's construction requirements are spread across several sections of its article. The question asks which of the listed features it has.",
    ("Final Exam #5", 21): "Service-entrance cable may also be used inside a building, but some loads can heat the conductors past their insulation rating. The question asks which loads the temperature rule mentions.",
    ("Final Exam #5", 22): "Only some insulation types are built for direct burial in earth. The question asks which of these cable types is approved for it.",
    ("Final Exam #5", 23): "Tray cable bending limits are set as a multiple of the cable's overall diameter, and shielded cable needs a larger bend. The question asks that multiple for cable with metallic shielding.",
    ("Final Exam #5", 24): "NM and NMC cables have a list of uses that are not permitted. The question asks which of these choices is on that list.",
    ("Final Exam #5", 32): "Trade size 3/8 flexible metal conduit is too small for the Chapter 9 fill tables, so it has its own table. The question asks the largest conductor that table allows.",
    ("Final Exam #5", 33): "Rigid metal conduit must carry manufacturer identification repeated along its length. The question asks the wording the marking rule uses.",
    ("Final Exam #5", 34): "Mixing metals can cause galvanic corrosion, so the Code names which fitting and raceway metals may be combined. The question asks what aluminum fittings and enclosures may be used with.",
    ("Final Exam #5", 35): "A pliable raceway is defined by how it can be bent. The question asks how, given that only reasonable force and no other help is allowed.",
    ("Final Exam #5", 36): "Rigid PVC has a list of permitted uses and a list of uses that are not permitted. The question asks which choice is permitted.",
    ("Final Exam #5", 37): "EMT construction is limited to a short list of metals. The question asks which of these materials are allowed.",
    ("Final Exam #5", 38): "Liquidtight flexible metal conduit is made for flexibility and wet locations, but it has a use that is not permitted. The question asks what that is.",
    ("Final Exam #5", 39): "Bare copper busbars are rated by amps per square inch of cross-section. The question gives the width and thickness and asks for the ampacity.",
    ("Final Exam #5", 48): "Bare live parts in auxiliary gutters must be spaced apart, with different clearances for parts on the same surface and parts held free in the air. The question asks the clearance for parts held free in the air.",
    ("Final Exam #5", 49): "Nonmetallic surface extensions may run from an existing outlet but must stay off and above the floor. The question asks how many inches above the floor they must stay.",
    ("Final Exam #5", 50): "Busway that passes from inside a building to outside moves air between the two sections unless something stops it. The question asks what must be installed at the wall.",
    ("Final Exam #5", 51): "Cablebus is a special assembly of spaced conductors in a ventilated housing. The question asks what kind of work it is limited to.",
    ("Final Exam #5", 52): "When a busway run steps down to a lower rating, the smaller section has to be protected somehow. The question asks what the Code requires at that reduction.",
    ("Final Exam #5", 53): "Surface strut-type channel raceway is strapped to the wall at set intervals and near each box. The question asks the maximum spacing between straps.",
    ("Final Exam #5", 54): "Engineered spacing documentation for overhead conductors belongs to one specific article. The question asks which article states it.",
    ("Final Exam #5", 55): "Surface nonmetallic raceways have a voltage limit between conductors unless listed for more. The question asks that limit.",
    ("Final Exam #5", 64): "Resistors and reactors run hot, so they need either distance from combustible material or a thermal barrier. The question asks the spacing below which a barrier is required.",
    ("Final Exam #5", 65): "Vertical runs of metal wireway need support at a set spacing and can have only one joint between supports. The question asks the maximum spacing.",
    ("Final Exam #5", 66): "Conductor fill for LFNC comes from a percentage-of-area table in Chapter 9. The question asks which table.",
    ("Final Exam #5", 67): "IMC risers for industrial machinery may be supported farther apart when threaded and firmly held at both ends. The question asks the maximum spacing in feet.",
    ("Final Exam #5", 68): "RMC in cinder fill must be protected from corrosion, and one option is a layer of noncinder concrete around it. The question asks how thick that layer must be.",
    ("Final Exam #5", 69): "NM cable in an accessible ceiling may be left unsupported for a short final run to equipment. The question asks the maximum distance from the last support.",
    ("Final Exam #5", 70): "Rigid PVC must be supported at intervals that grow with trade size. The question asks the spacing for 1/2-inch conduit.",
}

"""Per-question scene overrides. Used only where the article-family scene is wrong."""

SCENES = {
    ("Final Exam #5", 6): "Picture the end of an armored cable whipped into a box on equipment that vibrates or has to move. Strapping that last short tail tight would kill the flex, so the Code lets a short tail float free.",
}
