"""Hand-written human explanation of what each question asks. Never states the answer."""

GISTS = {
    ("Final Exam #3", 28): "Vending machines, tire pumps, and water coolers get touched by strangers all day long. The question asks which of these public machines needs fast-trip protection for people.",
    ("Final Exam #5", 6): "A short tail of armored cable left loose at a terminal so things can flex does not need strapping. The question asks how long that free tail may be.",

    ("Final Exam #1", 1): "Turn 60 percent into a fraction, then shrink it to lowest terms. Percent just means out of a hundred, so start there.",
    ("Final Exam #1", 2): "Some gear gets its wires landed from the back or the side. The factory must stamp a warning where you will see it before you ever open the doors. The question asks where that mark goes.",
    ("Final Exam #1", 3): "Your meter and tools need an outlet near the service gear. In bigger buildings the Code puts a limit on how far away it can be. The question asks what that limit is.",
    ("Final Exam #1", 4): "An office counts a fixed number of volt-amps for every square foot of floor. The question hands you 5,000 square feet and says to skip the demand math. Multiply and pick the total.",
    ("Final Exam #1", 5): "The meter says the switch has nothing across it and the bulb has full voltage, yet the bulb stays dark. Walk through what each of those readings proves, and the question answers itself.",
    ("Final Exam #1", 6): "Holiday lights still have to prove they were tested somewhere. The question asks what proof the Code wants on the product.",
    ("Final Exam #1", 7): "Wires packed inside switchgear live in heat and tight quarters. The question asks what quality the Code demands of those conductors.",
    ("Final Exam #1", 8): "Your deck needs its own outlet so nobody runs a cord out the window. The question asks how high off the deck floor that outlet may sit.",
    ("Final Exam #1", 9): "Wire colors are reserved: some mean neutral, one means ground, and the rest are free to be hot. The question asks which of these four may serve as a hot.",
    ("Final Exam #1", 10): "A 12-foot strip of outlets in a store will never all run at once. The rule counts every 5 feet, or fraction of it, as one outlet. The question asks how many volt-amps that works out to.",
    ("Final Exam #1", 11): "Bedroom walls need outlets close together, and the Code defines exactly which stretches of wall count. The question asks how wide a stretch has to be before it counts.",
    ("Final Exam #1", 12): "A garage floor is concrete, cars drip water, and you stand on the ground. The question asks which fast-acting protection that vacuum outlet needs.",
    ("Final Exam #1", 13): "This one needs its missing diagrams: an ammeter reads current and wires in series with the load. Without the pictures it cannot be answered, so flag it and move on.",
    ("Final Exam #1", 14): "Start from the table value, keep it untouched for 86 degrees since that is the table's own temperature, then shrink it because four wires share one pipe. The question asks what you land on.",
    ("Final Exam #1", 15): "Party-string lights hung overhead with no support wire still have to be thick enough not to snap. The question asks the thinnest wire the Code allows there.",
    ("Final Exam #1", 16): "A living tree sways and grows, so wires tied to it need slack hardware that moves instead of tearing. The question asks what that hardware is called.",
    ("Final Exam #1", 17): "Breakers come only in standard sizes, so circuits are named to match them. The question asks which of these lists is the true standard set.",
    ("Final Exam #1", 18): "An elevator motor yanks hard for a few seconds and then rests, nothing like a fan running all day. The question asks what the Code calls that kind of work cycle.",
    ("Final Exam #1", 19): "Watts equals volts times something, and the formula writes that something as the letter I. The question asks what I stands for.",
    ("Final Exam #1", 20): "Two ground rods driven too close together act like a single rod. The question asks how far apart they must stand so both actually work.",
    ("Final Exam #1", 21): "A house never runs its big range at full paper load, so the Code lets you count only part of it. The question asks what a 14 kW range counts as.",
    ("Final Exam #1", 22): "Even a two-car garage needs a place to plug in tools and chargers. The question asks the smallest number of outlets the Code demands in it.",
    ("Final Exam #1", 23): "Big feeders run as parallel sets in separate pipes, and each pipe needs its own fault path home. The question asks how the ground wire must be run through them.",
    ("Final Exam #1", 24): "Fountain water plus people means any nearby outlet needs fast-trip protection. The question asks how far from the water's edge that rule reaches.",
    ("Final Exam #1", 25): "A welder gulps huge current in short bursts, so its breaker is sized up from its rating plate. The question asks the biggest breaker allowed for a 43-amp welder.",
    ("Final Exam #1", 26): "The printing on a wire tells you what it is built of. The question asks what the dash-2 at the end of RHW-2 means.",
    ("Final Exam #1", 27): "Hot air steals a wire's capacity, so you shrink the table value by the temperature factor. Three of these wires at 112 degrees. The question asks what each one is still good for.",
    ("Final Exam #1", 28): "If a gas pump catches fire you need a kill switch close enough to reach but far enough to survive using. Twenty feet is the near limit in the question. It asks the far limit.",
    ("Final Exam #1", 29): "Pipes rising into the bottom of a big floor-standing panel cannot stick up too far inside or they hit the guts. The question asks how many inches above the bottom they may rise.",
    ("Final Exam #1", 30): "A thermostat can double as the heater's off switch, but only if OFF truly means off until a person touches it again. The question asks what the Code demands of that switch.",
    ("Final Exam #1", 31): "A long hallway with no outlet means extension cords across the walkway. The question asks how long a hallway must be before it earns its own outlet.",
    ("Final Exam #1", 32): "A short thin tap off a fat feeder has no real protection of its own, so the Code caps how big the feeder breaker feeding it may be. A 40-amp tap is given. The question asks that cap.",
    ("Final Exam #1", 33): "One hallway switch plus one stair switch running the same light takes three terminals on each switch. The question asks which standard switch type that is.",
    ("Final Exam #1", 34): "An outdoor cord must survive rain and sun, and the letters printed on it say what it survives. The question asks which of these four types is rated for wet and sunny.",
    ("Final Exam #1", 35): "A steel building column buried deep makes a fine ground, but only if enough of it is truly underground. The question asks how many feet must be in the earth.",
    ("Final Exam #1", 36): "A whole house never runs everything at once, so the main service wires may be a touch smaller than the breaker size. The question asks what share of the rating they may be.",
    ("Final Exam #1", 37): "A plastic tray full of cables must not carry fire along the ceiling. The question asks what the tray itself must be made of.",
    ("Final Exam #1", 38): "Underground feeder cable is built for wet, dry, and nasty soil. The question asks where the Code lets you run it, and three of these answers are places it forbids.",
    ("Final Exam #1", 39): "A controller guarding a whole group of motors must wear a marking that says what protection it gives. The question asks which word the Code requires in that marking.",
    ("Final Exam #1", 40): "Five dryers in one building never all heat at once, so you count only part of the total. The question asks what share five of them count as.",
    ("Final Exam #1", 41): "A stop button has to break the power path itself to kill the motor, and that only works one wiring way. The question asks which way.",
    ("Final Exam #1", 42): "Rain hits outdoor outlets, so the outlet itself must be built for wet places. Four similar-sounding labels are offered. The question asks which exact one the Code wants.",
    ("Final Exam #1", 43): "A fan hanging over a hot tub, with bathers who cannot step away from the water, must stay high when there is no fast-trip protection. The question asks the minimum height.",
    ("Final Exam #1", 44): "A hot wire touching metal it was never meant to touch has a specific name. The question describes exactly that and asks the name.",
    ("Final Exam #1", 45): "A disposal cord under the sink lives wet and gets yanked, so the Code caps its length at both ends. Eighteen inches is the short end, given in the question. It asks the long end.",
    ("Final Exam #1", 46): "Turn 40 percent into a fraction and shrink it to lowest terms.",
    ("Final Exam #1", 47): "This one needs its missing diagrams: a temperature switch symbol is a switch with a heat-sensing mark on it. Without the pictures it cannot be answered, so flag it and move on.",
    ("Final Exam #1", 48): "Small children poke things into outlets, so a normal hallway outlet in a house needs built-in shutters. The question asks which protection that 15-amp hallway outlet needs.",
    ("Final Exam #1", 49): "Concrete poured over a trench already shields the cable some, so less dirt is needed below it. The question asks how much cover still stays required.",
    ("Final Exam #1", 50): "Phone and cable-TV wires crossing over your roof must stay high enough that nobody touches them from the roof. The question asks that minimum height.",
    ("Final Exam #1", 51): "Big live gear can arc, and then you need to run through the door, not fumble with a knob. The question asks how close a door must be before it needs exit hardware that opens outward.",
    ("Final Exam #1", 52): "An outdoor disconnect box must sit high enough that water, snow, and mowers never reach into it. The question asks the minimum height of the box bottom.",
    ("Final Exam #1", 53): "Trains are tall steel, so wires crossing the tracks stay very high. The question asks the minimum clearance over the rails.",
    ("Final Exam #1", 54): "You normally may never splice a cord, except to rescue a tough work-site cord. The question asks which other cord type the Code also names for repair.",
    ("Final Exam #1", 55): "A nail or drywall screw can spear a cable stapled flat against a stud, so the Code holds the cable back from the stud edge. The question asks that setback distance.",
    ("Final Exam #1", 56): "A plain wall outlet feeding a small plug-in motor with no overload protection of its own cannot be very big, or a stalled motor burns the cord. The question asks the biggest outlet allowed there.",
    ("Final Exam #1", 57): "The space above a panel must stay clear so nothing drips, leaks, or falls onto live parts. Four candidates are offered. The question asks which one may share that space.",
    ("Final Exam #1", 58): "A transformer wears a nameplate with everything you need to size it. Three of these answers belong on it. The question asks which one does not.",
    ("Final Exam #1", 59): "A circuit gets its size name from one thing only, not its wire and not its outlets. The question asks what gives the circuit its rating.",
    ("Final Exam #1", 60): "Underground wires anywhere near a pool must keep their sideways distance so a fault cannot reach the water. The question asks how far out that zone goes.",
    ("Final Exam #1", 61): "Gas, dust, and fibers each get their own hazard class name. The question describes fibers and flyings and asks which class that is.",
    ("Final Exam #1", 62): "You lost 10 volts between the panel and the load. The question asks what share of the starting 125 volts that loss is. Loss divided by source.",
    ("Final Exam #1", 63): "A quarter inch on paper stands for a whole foot in the house. The question asks how long three and a half paper inches really is.",
    ("Final Exam #1", 64): "Big plan sets are read in a standard order so nothing gets missed. The question asks where you start.",
    ("Final Exam #1", 65): "House power flips direction 60 times a second, and the question wants a quarter of one flip. Work out how much time each quarter gets.",
    ("Final Exam #1", 66): "A short flexible whip running up to a light fixture does not need strapping every few feet. The question asks how long that free whip may be.",
    ("Final Exam #1", 67): "A very short pipe between two boxes is almost all open space, so the Code lets you pack it fuller than a long run. The question asks how full, as a percent.",
    ("Final Exam #1", 68): "The ground wire is picked from its own table by reading across from the breaker ahead of it. A 50-amp breaker is given. The question asks the copper size across from it.",
    ("Final Exam #1", 69): "A wooden sign box near hot lamp holders is kindling unless the wood keeps its distance. The question asks how far back the wood must stay.",
    ("Final Exam #1", 70): "Motor current comes from the Code's own table, never the nameplate, and a 480-volt system reads the 460-volt column. The question asks what a 50-horse wound-rotor motor reads there.",
    ("Open Book Exam #1", 7): "A switchboard is split into sections, and stray wires wandering through sections they do not serve cause faults and confusion. Only wires that actually end in a section may live there. The question asks which kind of section a wire must end in to sit there.",
    ("Open Book Exam #1", 1): "A shared-neutral circuit has two hots on one neutral. Kill only one side to work and the other side backfeeds the neutral. The question asks which wires the disconnect must open together.",
    ("Open Book Exam #1", 2): "At the main service, neutral and ground meet at exactly one point through one special link. The question asks the name of that link.",
    ("Open Book Exam #1", 3): "Floor area for load math is measured wall to wall, and it matters which face of the wall you use. The question asks which side you measure from.",
    ("Open Book Exam #1", 4): "A notch in a stud leaves the cable nearly exposed to drywall screws, so a steel plate guards it. The question asks how thick that plate must be.",
    ("Open Book Exam #1", 5): "Servicing a motor control center needs power nearby for tools and a meter. The question asks how close that outlet must be.",
    ("Open Book Exam #1", 6): "A light switch breaking a motor or ballast load fights arcing, so it cannot carry its full bulb rating. The question asks what share of its rating it may switch.",
    ("Open Book Exam #1", 8): "A flat plate ground only works in deep, permanently damp earth. The question asks how deep it must be buried.",
    ("Open Book Exam #1", 9): "Every neutral needs its own terminal screw in the panel, never doubled up with another wire. The question asks how the Code says each one must land.",
    ("Open Book Exam #1", 10): "Water plus outlets near a tub is the classic shock setup. The question asks how far from the tub edge the fast protection reaches.",
    ("Open Book Exam #1", 11): "An open panel in a hallway leaves live parts exposed to anyone walking by. The question asks what must be done with that working space while the guts are out.",
    ("Open Book Exam #1", 12): "A commercial kitchen is water, steel, and people in a hurry. The question asks which fixture triggers the protection rule there.",
    ("Open Book Exam #1", 13): "Load math does not need endless decimals. The question asks how small a fraction you may simply drop.",
    ("Open Book Exam #1", 14): "A crawl space is a damp dark hole you belly-crawl through past wires, so even the lights there get the fast protection. The question asks the voltage limit of that rule.",
    ("Open Book Exam #1", 15): "Gear wired from behind still has to warn you from where you stand. The question asks where the factory mark goes.",
    ("Open Book Exam #1", 16): "Your meter needs power near the service gear. The question asks the distance limit for that outlet.",
    ("Open Book Exam #1", 17): "Wires living inside switchgear sit in heat and tight quarters. The question asks what quality the Code demands of them.",
    ("Open Book Exam #1", 18): "Some outdoor outlets exist only so a serviceman can plug in tools. The question asks which kind of outlet the rule covers.",
    ("Open Book Exam #1", 19): "A bare bulb on a job site gets smashed by ladders and lumber. The question asks what the Code names as the required protection.",
    ("Open Book Exam #1", 20): "The washer gets a private circuit all to itself with nothing else on it. The question asks what size breaker feeds it.",
    ("Open Book Exam #1", 21): "Offices count a fixed number of volt-amps per square foot. Five thousand square feet, no demand math. Multiply and pick the total.",
    ("Open Book Exam #1", 22): "The washer outlet must sit near the washer, not across the room on an extension cord. The question asks the maximum distance allowed.",
    ("Open Book Exam #1", 23): "Holiday lights must prove they were tested. The question asks what proof the Code wants on the product.",
    ("Open Book Exam #1", 24): "Pool pump motors sit next to the water and run on serious current. The question asks up to what amperage the fast-trip rule reaches.",
    ("Open Book Exam #1", 25): "The AC disconnect must be visible from the unit and quick to reach. The question asks how reachable that disconnect must be.",
    ("Open Book Exam #4", 1): "Not everyone may touch live gear, only someone trained to see the danger coming. The question describes that worker and asks what the Code calls them.",
    ("Open Book Exam #4", 2): "Every outdoor outlet at a house gets the fast protection, up to a certain breaker size. The question asks where that cutoff sits.",
    ("Open Book Exam #4", 3): "Romex belongs in dry homes, not everywhere. Three of these places welcome it. The question asks which place forbids it.",
    ("Open Book Exam #4", 4): "Concrete over the trench already shields the cable, so less dirt is needed below it. The question asks how much cover still stays required.",
    ("Open Book Exam #4", 5): "Small children poke things into outlets, so a normal hallway outlet needs built-in shutters. The question asks what that 15-amp hallway outlet needs.",
    ("Open Book Exam #4", 6): "A disposal cord lives wet and gets yanked, so the Code caps its length at both ends. Eighteen inches is the short end. The question asks the long end.",
    ("Open Book Exam #4", 7): "A special outlet with an extra-clean ground for computers must be recognizable at a glance. The question asks what mark sits on its face.",
    ("Open Book Exam #4", 8): "A shared-neutral circuit may only feed plain 120-volt loads, never anything wired across the two hots. The question asks what kind of loads those are called.",
    ("Open Book Exam #4", 9): "A hot wire touching metal it was never meant to touch has a specific name. The question describes exactly that and asks the name.",
    ("Open Book Exam #4", 10): "Christmas tree lots get thrown up and torn down fast and rough, so splices there cannot float free. The question asks whether a box is optional or mandatory.",
    ("Open Book Exam #4", 11): "A fan over a hot tub with no fast-trip protection must stay high above bathers who cannot step away. The question asks the minimum height.",
    ("Open Book Exam #4", 12): "Arc protection must guard the whole circuit from the panel to the last outlet, not just part of it. The question asks what exactly gets that protection.",
    ("Open Book Exam #4", 13): "A sticker from a testing lab proves the gear was examined. The question describes that mark and asks what it is called.",
    ("Open Book Exam #4", 14): "Rain hits outdoor outlets, so the outlet itself must be built for wet places. Four similar labels are offered. The question asks which exact one the Code wants.",
    ("Open Book Exam #4", 15): "Five dryers in one building never all heat at once, so you count only part of the total. The question asks what share five of them count as.",
    ("Open Book Exam #4", 16): "A controller guarding a whole group of motors must wear a marking that says what protection it gives. The question asks which word the Code requires in that marking.",
    ("Open Book Exam #4", 17): "Underground feeder cable is built for wet, dry, and nasty soil. The question asks where it may run, and three answers are places it forbids.",
    ("Open Book Exam #4", 18): "Romex may drop into the top of a surface panel through short protective sleeves. The question asks the shortest those sleeves may be.",
    ("Open Book Exam #4", 19): "A light fixture hanging off a box needs real screws holding it, not tiny ones, and six pounds is the most this trick allows. The question asks the smallest screw size permitted.",
    ("Open Book Exam #4", 20): "A plastic tray full of cables must not carry fire along the ceiling. The question asks what the tray itself must be made of.",
    ("Open Book Exam #4", 21): "Snow-melt gear gets an outlet of its own, and how reachable it is decides the rule. The question asks which word fills the blank.",
    ("Open Book Exam #4", 22): "A whole house never runs everything at once, so the main service wires may be a touch smaller than the breaker size. The question asks what share of the rating they may be.",
    ("Open Book Exam #4", 23): "Arc protection covers nearly every room people live and sleep in. Three of these rooms need it. The question asks which one does not.",
    ("Open Book Exam #4", 24): "A steel building column buried deep makes a fine ground, but only if enough of it stands in the earth. The question asks how many feet must be buried.",
    ("Open Book Exam #4", 25): "An outdoor cord must survive rain and sun, and the letters printed on it say what it survives. The question asks which of these four types is rated for wet and sunny.",
    ("Open Book Exam #7", 1): "Neutral current must travel one continuous unbroken path back to the source. The question asks which word describes how that joining must be made.",
    ("Open Book Exam #7", 2): "Copper has a known resistance per thousand feet, and the Code parks it in a Chapter 9 table. The question asks which table holds it.",
    ("Open Book Exam #7", 3): "Big gear that gets worked on live must carry an arc-flash warning, except in one place on this list. The question asks which place is exempt.",
    ("Open Book Exam #7", 4): "An X-ray machine fires in violent split-second bursts, so its wires are sized to the burst rating, not the steady one. The question asks which demand rating that is.",
    ("Open Book Exam #7", 5): "Flood rules measure from the highest line water can reach before it spills over. The question asks the name of that level.",
    ("Open Book Exam #7", 6): "A job-built extension cord on a 20-amp circuit needs cord thick enough for the breaker behind it. The question asks the smallest wire size allowed.",
    ("Open Book Exam #7", 7): "Two breakers in a row only coordinate if nothing else taps in between them. The question asks what must not be connected alongside the downstream one.",
    ("Open Book Exam #7", 8): "Gear with cooling slots needs open air moving through it. The question asks what kind of openings trigger that rule.",
    ("Open Book Exam #7", 9): "A building's main switch must cover the whole computed load, no less. The question asks which load value sets its minimum size.",
    ("Open Book Exam #7", 10): "Heat rising off a heated ceiling cooks any wire lying on it. The question asks how far above it wiring must run.",
    ("Open Book Exam #7", 11): "Tool circuits feed many outlets, so the wire must at least match the breaker. The question asks the exact Code wording for that minimum.",
    ("Open Book Exam #7", 12): "Paint-thin enamel rust protection fails outdoors. The question asks which coating is indoor-only.",
    ("Open Book Exam #7", 13): "Burial depths live in one specific table. The question asks which table number holds them.",
    ("Open Book Exam #7", 14): "Conduit size names live in one specific table. The question asks which table number holds them.",
    ("Open Book Exam #7", 15): "You may start from the wire's own temperature rating, but the weakest link where it lands caps you. The question asks what that link is called.",
    ("Open Book Exam #7", 16): "When the lights die, people must find the backup power. The sign at the entrance names its type plus one more fact. The question asks what that fact is.",
    ("Open Book Exam #7", 17): "Lugs are tested to a temperature, and the wire must respect the lug's number. The question asks which word describes that published rating.",
    ("Open Book Exam #7", 18): "The total computed load divided by circuit size sets how many circuits a house gets, at a minimum. The question asks which word fills that blank.",
    ("Open Book Exam #7", 19): "Paint and plaster inside a panel are bad, but one contaminant eats metal alive. The question asks which one the Code names.",
    ("Open Book Exam #7", 20): "Part of a sign keeps the rain off but holds no electricity. The question asks what that part is called.",
    ("Open Book Exam #7", 21): "A transformer steps power down, and the panel protection goes on one side of it. The question asks which side.",
    ("Open Book Exam #7", 22): "An open panel door must never trap you: the escape path past it keeps a minimum width. The question asks how many inches wide.",
    ("Open Book Exam #7", 23): "High-voltage flexible cable terminations are for trained hands only. The question asks which cable type the rule covers.",
    ("Open Book Exam #7", 24): "One old 4-wire system has a wild leg with higher voltage to ground, and the gear must warn about it. The question asks what that system is called.",
    ("Open Book Exam #7", 25): "A building fed from several directions needs a map at every shutoff showing all the others. The question asks where that plaque goes.",
    ("Open Book Exam #10", 1): "Barn dust gets into motors and grinds them down. The question asks what the motor must be built to keep out.",
    ("Open Book Exam #10", 2): "Porches, garages, and dead space do not count as living area for load math. The question asks which of these stays out.",
    ("Open Book Exam #10", 3): "The green screw takes one wire only, and it must be the ground. The question asks which conductor that is.",
    ("Open Book Exam #10", 4): "Wires leaving an industrial panel are either full feeders or short taps with their own rules. The question asks which one these supply wires count as.",
    ("Open Book Exam #10", 5): "Buried pipe rots from the fill packed around it. The question asks what bad fill contributes to.",
    ("Open Book Exam #10", 6): "A device that trips a far-away disconnect through a relay has a name. The question describes it and asks the name.",
    ("Open Book Exam #10", 7): "Three of these statements are true Code. The question asks which one is false, so read each like its own true-or-false quiz.",
    ("Open Book Exam #10", 8): "A tray carrying welder cables must announce itself so nobody adds the wrong wires later. The question asks what the sign must say.",
    ("Open Book Exam #10", 9): "A ride or stand has exactly one person in charge of start, stop, and control. The question asks what the Code calls that person.",
    ("Open Book Exam #10", 10): "Wires near a loading door must stay clear sideways, and may never pass beneath the opening. Two rules, and both must hold. The question asks which installation obeys both.",
    ("Open Book Exam #10", 11): "A rooftop antenna is often the tallest metal around, and power lines arc to tall metal. The question asks above what voltage the power lines must be kept away from it.",
    ("Open Book Exam #10", 12): "Thermostat-type circuits get the easy rules only while they stay small in volts and in total power. Thirty volts is given. The question asks the volt-amp cap.",
    ("Open Book Exam #10", 13): "A small box hung on two well-supported pipes can float free, but only if the pipes bite in right. The question asks how those conduits must connect.",
    ("Open Book Exam #10", 14): "Hair-thin fixture wires on X-ray controls survive only behind a small breaker. The question asks the biggest breaker allowed.",
    ("Open Book Exam #10", 15): "Copper-coated aluminum wire must carry enough real copper skin to count. The question asks the minimum percent copper.",
    ("Open Book Exam #10", 16): "A concrete wall counts as grounded, and that changes the working-space depth you need. The question asks what concrete counts as.",
    ("Open Book Exam #10", 17): "Gas, dust, and fibers each get their own hazard class name. The question describes fibers and flyings and asks which class that is.",
    ("Open Book Exam #10", 18): "An isolated-ground outlet for computers carries a bright mark on its face. The question asks what that mark is.",
    ("Open Book Exam #10", 19): "A hospital bed runs life-support gear that cannot share or fail. The question asks the minimum outlets at each bed spot.",
    ("Open Book Exam #10", 20): "Your deck needs its own outlet, reachable and not too high. The question asks the maximum height above the deck floor.",
    ("Open Book Exam #10", 21): "Fire pump gear must sit above any floor water. The question asks how many inches up.",
    ("Open Book Exam #10", 22): "Two voltage levels sharing one pipe need cable built to keep them apart. The question asks which insulation type the rule covers.",
    ("Open Book Exam #10", 23): "Most RV spots need the standard 30-amp plug. The question asks what percent of sites must have it.",
    ("Open Book Exam #10", 24): "The wire tying the neutral side of the system to the earth rod has a name. The question asks what it is.",
    ("Open Book Exam #10", 25): "High-voltage burial eats through weak pipe, so sharp rocky fill is banned around it. The question asks what that fill can do to the raceway.",
}

"""Per-question scene overrides. Used only where the article-family scene is wrong."""

SCENES = {
    ("Final Exam #5", 6): "Picture the end of an armored cable whipped into a box on equipment that vibrates or has to move. Strapping that last short tail tight would kill the flex, so the Code lets a short tail float free.",
}
