"""Hand-written human explanation of what each question asks. Never states the answer."""

GISTS = {
    ("Final Exam #3", 28): "Vending machines, tire pumps, and water coolers are accessible to the general public. The question asks which of these public machines needs fast-trip protection for people.",
    ("Final Exam #5", 6): "A short length of armored cable at a terminal accommodates equipment movement and is exempt from securing. The question asks how long that free length may be.",

    ("Final Exam #1", 1): "Convert 60 percent to a fraction, then reduce to lowest terms. Percent means per hundred.",
    ("Final Exam #1", 2): "Some equipment requires rear or side access for field connections. The manufacturer must mark it where visible before the enclosure is opened. The question asks where that mark goes.",
    ("Final Exam #1", 3): "Service work requires a receptacle near the service equipment. In larger buildings the Code limits how far away it may be. The question asks what that limit is.",
    ("Final Exam #1", 4): "Office occupancies use a fixed volt-ampere value per square foot of floor area. The question hands you 5,000 square feet and says to skip the demand math. Multiply and pick the total.",
    ("Final Exam #1", 5): "With 0 volts across the switch and full voltage across the lamp, yet the lamp is dark: each reading narrows the fault location.",
    ("Final Exam #1", 6): "Seasonal decorative lighting requires evidence of testing. The question asks what proof the Code wants on the product.",
    ("Final Exam #1", 7): "Conductors inside switchgear operate at elevated temperature in restricted space. The question asks what quality the Code demands of those conductors.",
    ("Final Exam #1", 8): "A balcony, deck, or porch requires its own receptacle so no cord passes through a window or door. The question asks how high off the deck floor that outlet may sit.",
    ("Final Exam #1", 9): "Conductor insulation colors are restricted by function. The question asks which of these colors is permitted for ungrounded conductors.",
    ("Final Exam #1", 10): "A 12-foot multioutlet assembly in a commercial occupancy is not loaded simultaneously. The rule counts every 5 feet, or fraction of it, as one outlet. The question asks how many volt-amps that works out to.",
    ("Final Exam #1", 11): "Dwelling bedroom walls require receptacles at defined spacing, and only qualifying wall segments count toward it. The question asks how wide a stretch has to be before it counts.",
    ("Final Exam #1", 12): "An attached garage has a concrete floor exposed to moisture with occupants at ground potential. The question asks which fast-acting protection that vacuum outlet needs.",
    ("Final Exam #1", 13): "This one needs its missing diagrams: an ammeter reads current and wires in series with the load. Without the pictures it cannot be answered, so flag it and move on.",
    ("Final Exam #1", 14): "Start from the table ampacity; no temperature correction applies at 86 degrees, then apply the adjustment factor for four current-carrying conductors. The question asks what you land on.",
    ("Final Exam #1", 15): "String lighting suspended overhead without a separate support wire must meet a minimum conductor size. The question asks the thinnest wire the Code allows there.",
    ("Final Exam #1", 16): "Vegetation moves with growth and wind, so outdoor wiring on trees requires flexible attachment means. The question asks what that hardware is called.",
    ("Final Exam #1", 17): "Overcurrent devices are manufactured in standard ratings, and circuits are designated accordingly. The question asks which of these lists is the true standard set.",
    ("Final Exam #1", 18): "An elevator motor draws high current briefly and then rests, unlike continuous-duty loads. The question asks what the Code calls that kind of work cycle.",
    ("Final Exam #1", 19): "Power in watts is the product of volts and a second quantity represented by the letter I. The question asks what I stands for.",
    ("Final Exam #1", 20): "Two ground rods installed too close together function as a single electrode. The question asks how far apart they must stand so both actually work.",
    ("Final Exam #1", 21): "A household range never operates at full calculated load, so the Code permits a demand factor. The question asks what a 14 kW range counts as.",
    ("Final Exam #1", 22): "A residential garage requires receptacle outlets for tools and equipment. The question asks the smallest number of outlets the Code demands in it.",
    ("Final Exam #1", 23): "Parallel feeder sets run in separate raceways, and each raceway requires its own equipment grounding path. The question asks how the ground wire must be run through them.",
    ("Final Exam #1", 24): "A fountain places water and people together, so nearby receptacles require ground-fault protection. The question asks how far from the water's edge that rule reaches.",
    ("Final Exam #1", 25): "A welder draws high current intermittently, so its overcurrent protection is sized above the nameplate rating. The question asks the biggest breaker allowed for a 43-amp welder.",
    ("Final Exam #1", 26): "Conductor surface markings identify its construction and ratings. The question asks what the dash-2 at the end of RHW-2 means.",
    ("Final Exam #1", 27): "Elevated ambient temperature reduces conductor ampacity; apply the temperature correction factor to the table value. Three of these wires at 112 degrees. The question asks what each one is still good for.",
    ("Final Exam #1", 28): "Fuel dispensing areas require an emergency shutoff that is reachable during a fire yet positioned away from the hazard. Twenty feet is given as the near limit. The question asks the far limit.",
    ("Final Exam #1", 29): "Raceways entering the bottom of floor-standing equipment cannot extend so far inside that they interfere with internal components. The question asks how many inches above the bottom they may rise.",
    ("Final Exam #1", 30): "A thermostat may serve as the disconnect only with a maintained OFF position requiring manual reset. The question asks what the Code demands of that switch.",
    ("Final Exam #1", 31): "A hallway without a receptacle invites cord-connected loads across the walking path. The question asks how long a hallway must be before it earns its own outlet.",
    ("Final Exam #1", 32): "A small tap conductor off a larger feeder has no overcurrent protection of its own, so the Code limits the rating of the upstream feeder overcurrent device. A 40-amp tap is given. The question asks that cap.",
    ("Final Exam #1", 33): "A hallway switch and a stair switch controlling one luminaire each require three terminals. The question asks which standard switch type that is.",
    ("Final Exam #1", 34): "Outdoor flexible cords require weather-resistant construction identified by their type letters. The question asks which of these four types is rated for wet and sunny.",
    ("Final Exam #1", 35): "A structural steel column in contact with earth may serve as an electrode only with sufficient earth contact. The question asks how many feet must be in the earth.",
    ("Final Exam #1", 36): "A dwelling service is not loaded to full rating, so service conductors may be sized below the service rating within limits. The question asks what share of the rating they may be.",
    ("Final Exam #1", 37): "Cable trays must not propagate fire along their length. The question asks what the tray itself must be made of.",
    ("Final Exam #1", 38): "Type UF cable is rated for wet, dry, and corrosive soil conditions. The question asks where the Code lets you run it, and three of these answers are places it forbids.",
    ("Final Exam #1", 39): "A controller serving a motor group must display a marking identifying its protection. The question asks which word the Code requires in that marking.",
    ("Final Exam #1", 40): "Multiple household dryers do not operate simultaneously, so a demand factor applies. The question asks what share five of them count as.",
    ("Final Exam #1", 41): "A motor stop device must directly open the control circuit, which requires a specific wiring configuration. The question asks which way.",
    ("Final Exam #1", 42): "Outdoor receptacles exposed to weather require wet-location construction; several similar designations exist. The question asks which exact one the Code wants.",
    ("Final Exam #1", 43): "A paddle fan installed over a hot tub without ground-fault protection must meet a minimum mounting height above the water. The question asks the minimum height.",
    ("Final Exam #1", 44): "An unintentional connection between an ungrounded conductor and metal that is not meant to carry current has a specific defined term. The question describes exactly that and asks the name.",
    ("Final Exam #1", 45): "A waste-disposer cord in a damp location under strain has both minimum and maximum length limits. Eighteen inches is given as the minimum. The question asks the long end.",
    ("Final Exam #1", 46): "Convert 40 percent to a fraction and reduce to lowest terms.",
    ("Final Exam #1", 47): "This one needs its missing diagrams: a temperature switch symbol is a switch with a heat-sensing mark on it. Without the pictures it cannot be answered, so flag it and move on.",
    ("Final Exam #1", 48): "A 15-ampere hallway receptacle in a dwelling must meet child-protection construction requirements. The question asks which protection that outlet needs.",
    ("Final Exam #1", 49): "Concrete cover over a trench provides mechanical protection, reducing the required earth cover beneath it. The question asks how much cover still stays required.",
    ("Final Exam #1", 50): "Communications conductors crossing over a roof must maintain clearance above the roof surface. The question asks that minimum height.",
    ("Final Exam #1", 51): "Large energized equipment requires door hardware that permits immediate egress without special operation. The question asks how close a door must be before it needs that hardware.",
    ("Final Exam #1", 52): "An outdoor disconnect enclosure must be mounted with its bottom above moisture exposure and physical damage. The question asks the minimum height of the box bottom.",
    ("Final Exam #1", 53): "Railroad tracks carry tall rolling stock, so overhead conductors require substantial clearance. The question asks the minimum clearance over the rails.",
    ("Final Exam #1", 54): "Flexible cord splices are generally prohibited, with repair permitted only for specified hard-service cord types. The question asks which other cord type the Code also names for repair.",
    ("Final Exam #1", 55): "Fasteners can penetrate cables secured flat against framing, so the Code requires a setback from the framing edge. The question asks that setback distance.",
    ("Final Exam #1", 56): "A receptacle supplying a small motor without integral overload protection is limited in rating so a stalled motor cannot overheat the cord. The question asks the biggest outlet allowed there.",
    ("Final Exam #1", 57): "The dedicated space above electrical equipment must remain clear of foreign systems. The question asks which one may share that space.",
    ("Final Exam #1", 58): "A transformer nameplate carries its ratings; most listed items belong there. The question asks which one does not.",
    ("Final Exam #1", 59): "A branch circuit's rating is determined by a single element — not its conductors or outlets. The question asks what gives the circuit its rating.",
    ("Final Exam #1", 60): "Underground wiring near a pool must maintain horizontal separation so fault current cannot reach the water. The question asks how far out that zone goes.",
    ("Final Exam #1", 61): "Gases, dusts, and fibers are assigned separate hazardous-location classes. The question describes fibers and flyings and asks which class that is.",
    ("Final Exam #1", 62): "A 10-volt difference exists between the panel and the load. The question asks what share of the starting 125 volts that loss is. Divide volts lost by source volts.",
    ("Final Exam #1", 63): "The drawing scale equates one-quarter inch to one foot. The question asks how long three and a half paper inches really is.",
    ("Final Exam #1", 64): "Construction drawings are reviewed in a standard sequence. The question asks where you start.",
    ("Final Exam #1", 65): "Alternating current reverses 60 times per second; the question covers one quarter-cycle. Compute the duration of one quarter-cycle.",
    ("Final Exam #1", 66): "A short length of flexible raceway serving a luminaire is exempt from standard support intervals. The question asks how long that free length may be.",
    ("Final Exam #1", 67): "A short conduit section between enclosures permits a higher fill percentage than a complete conduit run. The question asks how full, as a percent.",
    ("Final Exam #1", 68): "The equipment grounding conductor is selected from its table using the upstream overcurrent device rating. A 50-amp breaker is given. The question asks the copper size across from it.",
    ("Final Exam #1", 69): "A wooden sign enclosure near hot lampholders is combustible and must maintain separation. The question asks how far back the wood must stay.",
    ("Final Exam #1", 70): "Motor current comes from the Code's own table, never the nameplate, and a 480-volt system uses the 460-volt column. The question asks what a 50-horse wound-rotor motor reads there.",
    ("Open Book Exam #1", 7): "Conductors passing through sections they do not terminate in create hazards. Only conductors terminating in a section may occupy it. The question asks which kind of section a wire must end in to sit there.",
    ("Open Book Exam #1", 1): "Opening only part of the circuit leaves the neutral energized from the other side. The question asks which wires the disconnect must open together.",
    ("Open Book Exam #1", 2): "At the service equipment, the neutral and ground systems connect at exactly one location. The question asks the name of that link.",
    ("Open Book Exam #1", 3): "Floor area for load math is measured wall to wall, and it matters which face of the wall you use. The question asks which side you measure from.",
    ("Open Book Exam #1", 4): "A notch in a stud leaves the cable nearly exposed to drywall screws, so a steel plate guards it. The question asks how thick that plate must be.",
    ("Open Book Exam #1", 5): "Motor control center servicing requires nearby power for test equipment. The question asks how close that outlet must be.",
    ("Open Book Exam #1", 6): "A snap switch interrupting motor or ballast loads is subject to arcing and is limited below its lamp rating. The question asks what share of its rating it may switch.",
    ("Open Book Exam #1", 8): "A plate electrode is effective only in permanently moist earth at sufficient depth. The question asks how deep it must be buried.",
    ("Open Book Exam #1", 9): "Each grounded conductor requires its own terminal, with no doubling under one screw. The question asks how the Code says each one must land.",
    ("Open Book Exam #1", 10): "Receptacles near a bathtub combine water and electricity access. The question asks how far from the tub edge the protection reaches.",
    ("Open Book Exam #1", 11): "An open panelboard exposes energized parts to passersby. The question asks what the working space requires during servicing.",
    ("Open Book Exam #1", 12): "A commercial kitchen is a wet environment with grounded surfaces and public occupancy. The question asks which fixture triggers the protection rule there.",
    ("Open Book Exam #1", 13): "Load calculations do not require extended decimal precision. The question asks how small a fraction you may simply drop.",
    ("Open Book Exam #1", 14): "A crawl space is a damp, restricted area; luminaires there still require ground-fault protection. The question asks the voltage limit of that rule.",
    ("Open Book Exam #1", 15): "Equipment with rear field connections must carry a marking visible before access. The question asks where the factory mark goes.",
    ("Open Book Exam #1", 16): "Test equipment requires a receptacle near service equipment. The question asks the distance limit for that outlet.",
    ("Open Book Exam #1", 17): "Conductors inside switchgear operate at elevated temperatures in confined space. The question asks what quality the Code demands of them.",
    ("Open Book Exam #1", 18): "Certain outdoor receptacles serve only maintenance equipment. The question asks which kind of outlet the rule covers.",
    ("Open Book Exam #1", 19): "A bare lamp on a construction site is exposed to physical damage. The question asks what the Code names as the required protection.",
    ("Open Book Exam #1", 20): "A laundry area requires a dedicated circuit serving no other loads. The question asks what size breaker feeds it.",
    ("Open Book Exam #1", 21): "Office occupancies use a fixed volt-ampere value per square foot. Five thousand square feet, no demand math. Multiply and pick the total.",
    ("Open Book Exam #1", 22): "The laundry receptacle must be located near the equipment it serves. The question asks the maximum distance allowed.",
    ("Open Book Exam #1", 23): "Seasonal decorative lighting requires evidence of testing. The question asks what proof the Code wants on the product.",
    ("Open Book Exam #1", 24): "Pool pump motors operate adjacent to water across a range of current ratings. The question asks up to what amperage the fast-trip rule reaches.",
    ("Open Book Exam #1", 25): "The disconnect must satisfy both visibility and accessibility conditions. The question asks how reachable that disconnect must be.",
    ("Open Book Exam #4", 1): "Only a trained worker capable of recognizing the hazards involved may access live equipment. The question describes that worker and asks what the Code calls them.",
    ("Open Book Exam #4", 2): "Dwelling outdoor receptacles require ground-fault protection within a defined overcurrent range. The question asks where that cutoff sits.",
    ("Open Book Exam #4", 3): "Type NM cable is limited to dry interior locations. Three of these places welcome it. The question asks which place forbids it.",
    ("Open Book Exam #4", 4): "Concrete above a trench provides protection that reduces the required earth cover beneath it. The question asks how much cover still stays required.",
    ("Open Book Exam #4", 5): "A 15-ampere hallway receptacle in a dwelling must meet child-protection construction requirements. The question asks what that outlet needs.",
    ("Open Book Exam #4", 6): "A waste-disposer cord operates in damp conditions under strain, so the Code limits its length at both ends. Eighteen inches is given as the short end. The question asks the long end.",
    ("Open Book Exam #4", 7): "An isolated-ground receptacle for sensitive equipment must be visibly identifiable. The question asks what mark sits on its face.",
    ("Open Book Exam #4", 8): "In a multiwire circuit, all conductors must originate from the same equipment. The question asks what that equipment must contain.",
    ("Open Book Exam #4", 9): "An unintentional connection between an ungrounded conductor and metal that is not meant to carry current has a specific defined term. The question describes exactly that and asks the name.",
    ("Open Book Exam #4", 10): "Seasonal lots are temporary installations with their own splicing rules. The question asks whether a box is optional or mandatory.",
    ("Open Book Exam #4", 11): "A fan over a hot tub without ground-fault protection must maintain height above occupants. The question asks the minimum height.",
    ("Open Book Exam #4", 12): "Arc-fault protection has a defined coverage scope along the circuit. The question asks what exactly gets that protection.",
    ("Open Book Exam #4", 13): "A mark from a testing laboratory shows the equipment was evaluated. The question describes that mark and asks what it is called.",
    ("Open Book Exam #4", 14): "Outdoor receptacles exposed to weather require wet-location construction; several similar designations exist. The question asks which exact one the Code wants.",
    ("Open Book Exam #4", 15): "Multiple dryers in a single building do not operate simultaneously, so a demand factor applies. The question asks what share five of them count as.",
    ("Open Book Exam #4", 16): "A controller serving a motor group must display a marking identifying its protection. The question asks which word the Code requires in that marking.",
    ("Open Book Exam #4", 17): "Type UF cable is rated for wet, dry, and corrosive soil. The question asks where it may run, and three answers are places it forbids.",
    ("Open Book Exam #4", 18): "Type NM cable may enter surface enclosures through short lengths of protective raceway. The question asks the shortest those sleeves may be.",
    ("Open Book Exam #4", 19): "A luminaire supported by an outlet box is limited to 6 lb and requires minimum-size screws. The question asks the smallest screw size permitted.",
    ("Open Book Exam #4", 20): "Cable trays must resist flame propagation. The question asks what the tray itself must be made of.",
    ("Open Book Exam #4", 21): "Snow-melting equipment requires a dedicated receptacle; the rule turns on how reachable it must be. The question asks which word fills the blank.",
    ("Open Book Exam #4", 22): "A dwelling service is not fully loaded, so its conductors may be sized below the service rating. The question asks what share of the rating they may be.",
    ("Open Book Exam #4", 23): "Arc-fault protection is required in most dwelling living areas. Three of these rooms need it. The question asks which one does not.",
    ("Open Book Exam #4", 24): "A structural steel column may serve as an electrode only with sufficient earth contact. The question asks how many feet must be buried.",
    ("Open Book Exam #4", 25): "Outdoor flexible cords require weather-resistant construction identified by their type letters. The question asks which of these four types is rated for wet and sunny.",
    ("Open Book Exam #7", 1): "Neutral current requires a continuous conductive path back to the source. The question asks which word describes how that joining must be made.",
    ("Open Book Exam #7", 2): "Copper conductor resistance values are tabulated in Chapter 9. The question asks which table holds it.",
    ("Open Book Exam #7", 3): "Equipment serviced while energized requires arc-flash labeling, with limited exceptions. The question asks which place is exempt.",
    ("Open Book Exam #7", 4): "X-ray equipment operates in brief high-current pulses, so conductors follow the pulse-based rating rather than the continuous one. The question asks which demand rating that is.",
    ("Open Book Exam #7", 5): "Floodplain measurements reference how high water can rise before spilling over. The question asks the name of that level.",
    ("Open Book Exam #7", 6): "A field-assembled extension cord must use conductors sized for the circuit rating. The question asks the smallest wire size allowed.",
    ("Open Book Exam #7", 7): "Two overcurrent devices in series coordinate only with no other connections between them. The question asks what must not be connected alongside the downstream one.",
    ("Open Book Exam #7", 8): "Ventilated equipment requires unobstructed airflow. The question asks what kind of openings trigger that rule.",
    ("Open Book Exam #7", 9): "Service equipment must be rated not less than the total computed load. The question asks which load value sets its minimum size.",
    ("Open Book Exam #7", 10): "A heated ceiling subjects overlying wiring to elevated temperature. The question asks how far above it wiring must run.",
    ("Open Book Exam #7", 11): "Multi-outlet tool circuits require conductors rated at least for the branch-circuit protection. The question asks the exact Code wording for that minimum.",
    ("Open Book Exam #7", 12): "Thin paint-type coatings do not qualify as outdoor corrosion protection. The question asks which coating is indoor-only.",
    ("Open Book Exam #7", 13): "Burial depths live in one specific table. The question asks which table number holds them.",
    ("Open Book Exam #7", 14): "Conduit size names live in one specific table. The question asks which table number holds them.",
    ("Open Book Exam #7", 15): "Conductors may start from their own temperature rating, but the lowest temperature rating in the chain caps the final ampacity. The question asks what that link is called.",
    ("Open Book Exam #7", 16): "During normal power loss, occupants must locate the emergency supply. The sign at the entrance names its type plus one more fact. The question asks what that fact is.",
    ("Open Book Exam #7", 17): "Terminations are rated for a temperature that limits conductor selection. The question asks which word describes that published rating.",
    ("Open Book Exam #7", 18): "The dwelling's required branch-circuit count is the total computed load divided by the circuit rating. The question asks which word fills that blank.",
    ("Open Book Exam #7", 19): "Foreign materials inside a panel are prohibited, and one listed contaminant causes corrosion. The question asks which one the Code names.",
    ("Open Book Exam #7", 20): "One part of a sign provides weather protection without containing electrical components. The question asks what that part is called.",
    ("Open Book Exam #7", 21): "A transformer changes the voltage level, and overcurrent protection is required on a specific side. The question asks which side.",
    ("Open Book Exam #7", 22): "Open equipment doors must not block egress; the passage width has a minimum. The question asks how many inches wide.",
    ("Open Book Exam #7", 23): "High-voltage flexible cable terminations are restricted to qualified personnel. The question asks which cable type the rule covers.",
    ("Open Book Exam #7", 24): "One 4-wire system includes a high leg with elevated voltage to ground, requiring identification. The question asks what that system is called.",
    ("Open Book Exam #7", 25): "A building with multiple supplies must document all sources at every shutoff point. The question asks where that plaque goes.",
    ("Open Book Exam #10", 1): "Agricultural buildings contain dust that can enter motor enclosures. The question asks what the motor construction must exclude.",
    ("Open Book Exam #10", 2): "Porches, garages, and unfinished spaces are excluded from habitable-area load calculations. The question asks which of these stays out.",
    ("Open Book Exam #10", 3): "The green screw accepts exactly one conductor. The question asks which conductor that is.",
    ("Open Book Exam #10", 4): "Conductors leaving an industrial panel fall into two classifications, each with its own rules. The question asks which one these supply wires count as.",
    ("Open Book Exam #10", 5): "Buried raceways corrode from aggressive backfill. The question asks what harmful backfill causes.",
    ("Open Book Exam #10", 6): "A device that opens a remote disconnect through a control relay has a defined term. The question describes it and asks the name.",
    ("Open Book Exam #10", 7): "Three of these statements reflect Code requirements. The question asks which one is false, so read each like its own true-or-false quiz.",
    ("Open Book Exam #10", 8): "A cable tray containing welder conductors must be marked to prevent adding incompatible wiring. The question asks what the sign must say.",
    ("Open Book Exam #10", 9): "An amusement ride has exactly one person responsible for starting, stopping, and controlling it. The question asks what the Code calls that person.",
    ("Open Book Exam #10", 10): "Conductors near a loading dock door must maintain side clearance and never run beneath the opening. Two rules, and both must hold. The question asks which installation obeys both.",
    ("Open Book Exam #10", 11): "A rooftop antenna is frequently the highest metal structure, so separation from power conductors is required above a voltage threshold. The question asks above what voltage the power lines must be kept away from it.",
    ("Open Book Exam #10", 12): "Control circuits use relaxed rules only within voltage and power limits. Thirty volts is given. The question asks the volt-amp cap.",
    ("Open Book Exam #10", 13): "A box carried only by its two conduit entries is exempt from separate support given compliant joints. The question asks how those conduits must connect.",
    ("Open Book Exam #10", 14): "Small-gauge X-ray control conductors require low-rated overcurrent protection. The question asks the biggest breaker allowed.",
    ("Open Book Exam #10", 15): "Copper-clad aluminum conductors require a minimum copper percentage. The question asks the minimum percent copper.",
    ("Open Book Exam #10", 16): "With a concrete wall opposite the equipment, the required working depth changes. The question asks what concrete counts as.",
    ("Open Book Exam #10", 17): "Gases, dusts, and fibers are assigned separate hazardous-location classes. The question describes fibers and flyings and asks which class that is.",
    ("Open Book Exam #10", 18): "An isolated-ground receptacle bears an identification mark on its face. The question asks what that mark is.",
    ("Open Book Exam #10", 19): "A hospital bed location serves critical equipment requiring dedicated, reliable receptacles. The question asks the minimum outlets at each bed spot.",
    ("Open Book Exam #10", 20): "A deck requires its own accessible receptacle within a maximum height. The question asks the maximum height above the deck floor.",
    ("Open Book Exam #10", 21): "Fire pump equipment must be elevated above potential standing water. The question asks how many inches up.",
    ("Open Book Exam #10", 22): "Two voltage levels in one raceway require cable with suitable separation construction. The question asks which insulation type the rule covers.",
    ("Open Book Exam #10", 23): "Recreational-vehicle sites predominantly require 30-ampere receptacles. The question asks what percent of sites must have it.",
    ("Open Book Exam #10", 24): "The conductor joining the system neutral to earth has a defined term. The question asks what it is.",
    ("Open Book Exam #10", 25): "High-voltage raceways require clean backfill; unsuitable material damages the raceway. The question asks what that fill can do to the raceway.",
}

"""Per-question scene overrides. Used only where the article-family scene is wrong."""

SCENES = {
    ("Final Exam #5", 6): "Picture the end of an armored cable whipped into a box on equipment that vibrates or has to move. Strapping that last short tail tight would kill the flex, so the Code lets a short tail float free.",
}
